### ISSUE TITLE
Gitlab Runner + Sysbox fail to set volume permissions

### ISSUE THREAD

**Issue by Exchizz** [nestybox/sysbox#122]
Hi,
I've completed the steps listed in: https://blog.nestybox.com/2020/10/21/gitlab-dind.html#gitlab-runner-deploys-jobs-in-system-containers (It's really good reading!)
When I try to run a build, gitlab-runner failes with the following error:
``
WARNING: Preparation failed: adding cache volume: set volume permissions: running permission container "19d34278bd14d99363c7f03e49c5f178c38e508fbfa755143eed00fe543a23f7" for volume "runner-twkxhdzq-project-504-concurrent-0-cache-3c3f060a0374fc8bc39395164f415a70": starting permission container: Error response from daemon: OCI runtime create failed: container_linux.go:364: starting container process caused "process_linux.go:533: container init caused \"process_linux.go:504: handleReqOp caused \\\"rootfs_init_linux.go:249: bind mounting /var/lib/docker/containers/19d34278bd14d99363c7f03e49c5f178c38e508fbfa755143eed00fe543a23f7/mounts/shm to dev/shm caused \\\\\\\"lstat /var/lib/docker/containers/19d34278bd14d99363c7f03e49c5f178c38e508fbfa755143eed00fe543a23f7/mounts: permission denied\\\\\\\"\\\"\"": unknown (linux_set.go:100:1s)  job=7871 project=504 runner=twkxHdzQ
``

If I use runc it works just fine and I can complete the build.

/etc/docker/daemon.json:
```
{
    "default-runtime": "sysbox-runc",
    "runtimes": {
        "sysbox-runc": {
            "path": "/usr/local/sbin/sysbox-runc"
        }
    },
    "bip": "172.20.0.1/16",
    "default-address-pools": [
        {
            "base": "172.25.0.0/16",
            "size": 24
        }
    ]
}
```

/etc/gitlab-runner/config.toml:
```
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "CloudRunnerVM"
  url = "https://gitlab.server"
  token = "token"
  executor = "docker"
  [runners.docker]
    tls_verify = true
    image = "docker:19.03.12"
    privileged = false
    disable_cache = false
    volumes = ["/cache", "/certs/client"]
    runtime = "sysbox-runc"
```

.gitlab-ci.yml:
```
image: docker:19.03.12
services:
  - docker:19.03.12-dind
build:
    stage: build
    script:
      - docker run -i -t ubuntu date
```

Gitlab-runner version: 13.5.0
Docker version: 19.03.13
sysbox version: 0.2.1-0

**Comment by ctalledo** [comment]
Hi @Exchizz ,

Thanks for giving Sysbox a shot. 

I recall bumping into this same issue and fixing it a few weeks ago. The fix is here:

https://github.com/nestybox/sysbox-runc/commit/bed8a8340261ed856e334ea8bd4cd303c61e151d

The fix was upstreamed to the Sysbox repo, but we've not yet generated a packaged Sysbox version that has it. We generate the packaged versions every couple of months or so.

For now, you'll need to build Sysbox from source in order to get the fix. It's pretty easy to do this, the instructions are here:

https://github.com/nestybox/sysbox/blob/master/docs/developers-guide/build.md

Let me know if this works for you.

**Comment by Exchizz** [comment]
Hi @ctalledo,
That has to be the fastest reply in the history of github - thank you.
I've compiled the source by following your guide, and it works :)

**Comment by ctalledo** [comment]
> That has to be the fastest reply in the history of github - thank you.

👍 

> I've compiled the source by following your guide, and it works :)

Beautiful, glad you got that going!

Closing this issue!
