### ISSUE TITLE
Is there a way to move /var/lib/sysbox to other places?

### ISSUE THREAD

**Issue by SoloGao** [nestybox/sysbox#135]
Hello, we are running sysbox with ubuntu focal. Due to limited / size, we opt to use /workspace/docker(which is a raid-0 ssd array) for docker storage. However, when running docker pull in system container, we found / is full. After further investigation, the image is saved in /var/lib/sysbox. So is there a way to move /var/lib/sysbox also to /workspace/sysbox? If not, will manually mount /var/lib/docker for system container work? Thanks

**Comment by ctalledo** [comment]
Hi @SoloGao, thanks for using Sysbox, hope you are finding it useful.

As you mentioned, when running Docker-in-Docker, Sysbox stores the inner Docker images in its data-store, which is currently fixed to the `/var/lib/sysbox` directory. These images remain there until the outer container is removed. 

> So is there a way to move /var/lib/sysbox also to /workspace/sysbox

Sysbox does not (yet) have a config flag to configure the location of it's data store (i.e., which is currently fixed to `/var/lib/docker`). It's something we need to add, and I'll use this issue to track it.

>  If not, will manually mount /var/lib/docker for system container work? 

Yes, that should work. You can always mount a docker volume or host directory in the outer container's `/var/lib/docker`. Not only does this allow you to select where you want the inner docker images stored, but also allows you to cache inner container images across container lifecycles. 

The Sysbox quick start guide shows how to do this:

https://github.com/nestybox/sysbox/blob/master/docs/quickstart/dind.md#persistence-of-inner-container-images-using-docker-volumes

Hope that helps!

**Comment by ctalledo** [comment]
FYI: The following PRs added a command line option (`--data-root`) to the sysbox-mgr to select the Sysbox data store:

https://github.com/nestybox/sysbox-mgr/pull/11
https://github.com/nestybox/sysbox/pull/142

The remaining action item is to document how to use it.

**Comment by ctalledo** [comment]
> The remaining action item is to document how to use it.

Done:

https://github.com/nestybox/sysbox/blob/master/docs/user-guide/configuration.md#sysbox-data-store-configuration


Closing!
