### ISSUE TITLE
Extend Sysbox to provide a json logging option

### ISSUE THREAD

**Issue by rodnymolina** [nestybox/sysbox#138]
[ requested by @kylecarbs ]

Sysbox should provide an option to log information in JSON format to ease log-parsing logic in user's monitoring tools.

**Comment by ctalledo** [comment]
This was completed in both sysbox-mgr and sysbox-fs:

sysbox-mgr commit: c5e2b1c
sysbox-fs commit: 4cef572

A new `log-format` command line option was added to both of these to control the log format (e.g., text or json).

Closing.
