### ISSUE TITLE
Unexpected error during NotifRespond() with invalid argument

### ISSUE THREAD

**Issue by yourapiexpert** [nestybox/sysbox#174]
Hi!

I am trying to incorporate sysbox in to buildroot on a custom kernel and for the most part it is going okay.

The kernel is 5.4.81 and I have ported shiftfs from Ubuntu in to the kernel as well as enabled all SECCOMP config options.  Sysbox is build from the Makefile and the completed binaries from the docker file included in the final output as well as systemd unit files.

The good news is everything runs.  sysbox-mgr and sysbox-fs are started at boot and specifying sysbox-runc as the runtime correctly initializes the container.

The problem is, however, when it comes to doing any type of file operations.  In the logs of sysbox-fs.log I see:

Unexpected error during NotifRespond() execution (invalid argument) on fd 13 pid 3289

With the result that any operation requiring writing files (apk add, for example) is halted inside the container.

I've spent two days prodding this and that with no success.  Is there any recommendation on what I can do to assist in debugging or any ideas of where to look further?

Any help would be greatly appreciated :)

**Comment by rodnymolina** [comment]
Stephen (@yourapiexpert), thanks for giving Sysbox a shot.

For distros different than Ubuntu, Sysbox [requires](https://github.com/nestybox/sysbox/blob/master/docs/distro-compat.md) kernel 5.5+. Sysbox relies on [seccomp-bpf](https://elixir.bootlin.com/linux/v5.5/source/include/uapi/linux/seccomp.h#L106) features to intercept a few syscalls, so this is probably the reason you are observing these errors.

Please let us know if this doesn't solve the problem for you.

**Comment by yourapiexpert** [comment]
You Sir are a scholar and a gentlemen!

I have not bumped up to 5.5 (yet) but you have definitely pointed me to an area where my kernel and that of Ubuntu's 5.4x are vastly different and the stock kernel I have here is certainly missing the code for notifications.

I will persist for a little bit putting the patches in place.  I am a bit committed to the 5.4 branch due to the LTS for the moment but I thank you for the fresh pair of eyes and advice.

-- Stephen

**Comment by rodnymolina** [comment]
Understood.

Just to clarify my previous point. The official/upstream 5.4 kernel has most of the seccomp-bpf features that we need, but not all of them; `SECCOMP_USER_NOTIF_FLAG_CONTINUE` was only added starting with 5.5. Now, Ubuntu's kernels incorporated all this logic way earlier -- as early as 5.2 I believe. That's the reason we support relatively old releases such as Ubuntu Bionic.

Let us know if there's anything we can help you with. Will keep this issue opened for a few days in case you want to use it as our communication channel (we're in [slack](https://nestybox-support.slack.com/join/shared_invite/enQtOTA0NDQwMTkzMjg2LTAxNGJjYTU2ZmJkYTZjNDMwNmM4Y2YxNzZiZGJlZDM4OTc1NGUzZDFiNTM4NzM1ZTA2NDE3NzQ1ODg1YzhmNDQ#/) too btw).

**Comment by yourapiexpert** [comment]
Thank you very much.

Well after some patching and a recompile I can confirm that I have very different results and can now run a container (I used docker:dind per the examples) and it appears to be far more successful than previous attempts.

I am not 100% sure I have all the correct code in all the required places so for any folks reading this please take up the advice and perhaps use the 5.5 kernel as your base if you can.

Sincere appreciation for all the assistance.  I think we're good to close this :)

**Comment by rodnymolina** [comment]
Backporting seccomp-bpf logic among major kernel-releases doesn't sound like a trivial task, great job!

If you are able to pass our integration-test suites (make test), i'd say you are in pretty good shape.
