### ISSUE TITLE
CNCF SIG-Runtime Presentation/Discussion(?)

### ISSUE THREAD

**Issue by raravena80** [nestybox/sysbox#175]
Hello Sysbox team,

I'm one of the co-chairs of the CNCF SIG-Runtime, I'm reaching out and I think it would be great for you to present/discuss the project at one of our meetings. For example, discuss things such as architecture overview and use cases.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by ctalledo** [comment]
Hi @raravena80 , thanks for reaching out, we would be very happy to present at the CNCF SIG runtime meeting and would love to get your feedback.

I've added a meeting date to the agenda (Thursday 02/04/2021). 

Thanks again!

**Comment by raravena80** [comment]
@ctalledo awesome! Looking forward!

**Comment by ctalledo** [comment]
Had a meeting with the CNCF to present on Sysbox on 02/04/2021. Thanks @raravena80 for the opportunity, hope you found it interesting!

Closing this issue!
