### ISSUE TITLE
encountered problem using docker-in-docker for Hyperledger Fabric

### ISSUE THREAD

**Issue by sxguan** [nestybox/sysbox#185]
Still reporting an error, when I execute the following commands first(The following commands are official test network).
```
curl -sSL https://bit.ly/2ysbOFE | bash -s
cd fabric-samples/test-network
./network.sh up 
./network.sh up 
```

**Comment by sxguan** [comment]
The previous issue  is [https://github.com/nestybox/sysbox/issues/177](url)

**Comment by sxguan** [comment]
Still reporting
```
bash-5.0# peer lifecycle chaincode install sacc.tar.gz
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image build failed: docker build failed: Error returned from build: 1 "failed to initialize build cache at /home/chaincode/.cache/go-build: mkdir /home/chaincode/.cache: permission denied"
```

**Comment by rodnymolina** [comment]
Hi @sxguan, question, are you now building Sysbox from sources or are you using our debian package installer? I'm asking coz i was not able to reproduce this issue with Sysbox's latest code (as mentioned in the previous [issue](https://github.com/nestybox/sysbox/issues/177)).

**Comment by sxguan** [comment]
I build Sysbox with your debian package installer.The problem is I can do [https://github.com/nestybox/sysbox/issues/177](url)successfully.But when I execute the following commands first, and then exectue [https://github.com/nestybox/sysbox/issues/177](url),reporting the error.
```
curl -sSL https://bit.ly/2ysbOFE | bash -s
cd fabric-samples/test-network
./network.sh up 
./network.sh down
```

**Comment by rodnymolina** [comment]
@sxguan, question:

Are you building from sources or are you installing Sysbox from our debian-installer? If you are using the installer, please follow the instructions below to build and launch Sysbox.

```
# Start by uninstalling Sysbox:
$ sudo apt-get purge sysbox -y

# Clone, build and re-launch Sysbox:
$ git clone --recursive git@github.com:nestybox/sysbox.git
$ cd sysbox
$ make sysbox && sudo make install
$ sudo scr/sysbox 
```

See more details [here](https://github.com/nestybox/sysbox/blob/master/docs/developers-guide/build.md).

Please let me know if you are able to reproduce the issue with our latest code.
