### ISSUE TITLE
Error while dialing dial unix /run/sysbox/sysfs.sock

### ISSUE THREAD

**Issue by myugan** [nestybox/sysbox#219]
Hi @ctalledo @rodnymolina 

I have another issue that's newly emerged and this one causes the container fails when creating from Docker API. Basically, my sysbox service is auto restart as you guys said before so that's fine, what I'm thinking is it possible for sysbox can do self-healing to creating the container if something happens? I'm not sure about these things or maybe another solution to solve this one?

Our backend is connected with Docker API, and this is the log from Sentry.
```
"OCI runtime create failed: failed to pre-register with sysbox-fs: failed to register container with sysbox-fs: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/sysbox/sysfs.sock: connect: connection refused": unknown"
```

**Comment by rodnymolina** [comment]
Hi @myugan, please see some questions below ...

*  I guess that by 'self-healing' you are referring to Sysbox finding a way to allow the existing containers to keep on operating normally. IOW, ensure that Sysbox daemon's restarts are not impacting the sys containers. Currently we don't have this functionality, but it's definitely something in our radar.

* Is this problem particular problem a one-off thing, or it's consistently reproduced?The error log above most likely indicates that sysbox-fs was down by the time a new sys container was created. Can you please collect the sysbox-fs logs next time you reproduce it?

**Comment by myugan** [comment]
In the log, related to a specific time that occurs the error I just see this, 

```
{"level":"warning","msg":"Sysbox-fs first child process error status: pid = 3774","time":"2021-01-21 12:13:02"}
{"level":"warning","msg":"Sysbox-fs first child process error status: pid = 3789","time":"2021-01-21 12:13:02"}
{"level":"warning","msg":"Sysbox-fs first child process error status: pid = 3888","time":"2021-01-21 12:13:02"}
{"level":"info","msg":"reaper: reaped pid 3775","time":"2021-01-21 12:13:03"}
{"level":"info","msg":"reaper: reaped pid 3790","time":"2021-01-21 12:13:03"}
{"level":"info","msg":"reaper: reaped pid 3889","time":"2021-01-21 12:13:03"}
{"level":"info","msg":"reaper: nothing to reap","time":"2021-01-21 12:13:03"}
```

Another log is in the normal state that tells us `Container unregistration completed:` and `Container registration completed:`

**Comment by rodnymolina** [comment]
@myugan, just fyi, I went ahead and created this [issue](https://github.com/nestybox/sysbox/issues/227) to track Sysbox's graceful-restart feature.

In regards to the issue you reported above, have you reproduced it again? Please make sure you collect the entire content of both sysbox-fs and sysbox-mgr files when this happens.

**Comment by myugan** [comment]
thanks again @rodnymolina, unfortunately, I can't reproduce it it seems like race conditions sometimes appear and another one will appear also I'm thinking if it's related to sysctl config maybe you can add the warning message to check the minimum value from kernel config to run sysbox nicely like the previous issue https://github.com/nestybox/sysbox/issues/195

**Comment by rodnymolina** [comment]
Problem hasn't been reproduced for a quite a while now. Please reopen it otherwise. Closing issue now.
