### ISSUE TITLE
using sysbox runc in arm64

### ISSUE THREAD

**Issue by wangweisong** [nestybox/sysbox#253]
Is sysbox supported arm64 platform? How to using sysbox in arm64?

**Comment by rodnymolina** [comment]
@wangweisong, Sysbox should, in principle, run in arm64, but we haven't tested it yet, so I wouldn't expect major issues to pop up (if any). If curious, you can build Sysbox and try it yourself.

This is definitely part of our roadmap, but its priority will depend on the interest we perceive from the community. If you don't mind me asking, what's the use-case that you have in mind?

Thanks.

**Comment by rodnymolina** [comment]
@wangweisong, I just realized that my suggestion to build and test Sysbox in arm64 is not feasible right now as our build & test framework has been written with only amd64 in mind. We need to enhance this as a next step towards full arm-arch support.

FYI, I just created this separate [issue](#258) to track this effort.

**Comment by ctalledo** [comment]
Tracked by issue #258. Closing as duplicate.
