### ISSUE TITLE
Sysbox installer: Add jq dependency for postinst/postrm debian scripts or replace jq with shell commands

### ISSUE THREAD

**Issue by nudgegoonies** [nestybox/sysbox#256]
You replaced the jq script in the config debian script with shell commands. But the jq command is still used within the postinst and postrm scripts.

Please add jq debian package as dependency or replace jq with shell commands in postinst and postrm scripts as well.

**Comment by ctalledo** [comment]
I think `jq` will need to be added as a dependency then, because the Sysbox installer needs it to configure the Docker daemon.

**Comment by rodnymolina** [comment]
`jq` has always been a Sysbox dependency, and that's still the case.

The changes we did in the latest release allowed us to remove `jq` from the debian-preconfig installation phase to avoid some dependency issues by following debian's package-policy guidelines. But `jq` is still a dependency for all other installation phases (preinst, postinst, etc). 

@nudgegoonies, can you please elaborate what you mean?

```
$ sudo apt-get install ./deb/debbuild/ubuntu-focal/sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'sysbox-ce' instead of './deb/debbuild/ubuntu-focal/sysbox-ce_0.3.0-0.ubuntu-focal_amd64.deb'
The following additional packages will be installed:
  jq
The following NEW packages will be installed:
  jq sysbox-ce
0 upgraded, 2 newly installed, 0 to remove and 252 not upgraded.
Need to get 0 B/26.8 MB of archives.
...
```

**Comment by nudgegoonies** [comment]
Sorry, i only looked into the Depends line and not into the Pre-Depends line which - was my recommendation :man_facepalming:

Can be closed!
