### ISSUE TITLE
Extend Sysbox support to ARM platforms

### ISSUE THREAD

**Issue by rodnymolina** [nestybox/sysbox#258]
By expanding Sysbox support to ARM platforms we are offering a more suitable alternative to virtual-machines in hardware-constrained environments.

There are three main goals needed to complete this task:

* Enhance the current build-framework to eliminate all amd64-specific instructions (e.g., fetched docker images should match the required arch).

* Extend build-framework to habilitate cross-compilation features.

* Validate the proper operation of Sysbox on arm64 platforms.

**Comment by abalmos** [comment]
@rodnymolina I am very interested in armhf and arm64 support. Is there a way to help? Is this a considerable effort? Could you mentor the issue?

**Comment by rodnymolina** [comment]
@abalmos, sure, let's talk. Please join our [slack](https://nestybox-support.slack.com/join/shared_invite/enQtOTA0NDQwMTkzMjg2LTAxNGJjYTU2ZmJkYTZjNDMwNmM4Y2YxNzZiZGJlZDM4OTc1NGUzZDFiNTM4NzM1ZTA2NDE3NzQ1ODg1YzhmNDQ#/) when have a chance, I'd like to start by understanding the use-case that you have in mind.

**Comment by ctalledo** [comment]
The upcoming Sysbox v0.5.0 release will add ARM support.

**Comment by ctalledo** [comment]
Sysbox support for ARM is already in the upstream code, so marking this issue as "Done".
