### ISSUE TITLE
Sysbox and kindest/node image incompatibility issue with latest v1.2x images

### ISSUE THREAD

**Issue by rodnymolina** [nestybox/sysbox#301]
Due to the latest changes in Kind's docker-images entrypoints, Sysbox is not able to launch Kind's images, nor able to wrap Kind's images with our own Sysbox [images](https://github.com/nestybox/dockerfiles/blob/9d74469c31c2d1fa8cc9f1cbf3ed69c41c7c5bf1/kindestnode/1.19/Dockerfile) as we have been doing since day one.

Kind's latest entrypoint modifications condition the support of user-namespaces to the activation of cgroup-v2 in the system. This approach conflicts with Sysbox as user-namespaces feature is always supported regardless of the cgroup configuration of the system. Aside from that, Sysbox doesn't support cgroup-v2 (yet), so currently we can't meet this requirement imposed by Kind.

For the time being we will continue to provide 'kindest/node' images as thin wrappers over Kind's ones. In the future, once all the above issues are solved, Sysbox users should be able to make direct use of Kind images -- although technically speaking that will always depend on the restrictions/assumptions imposed by Kind's images entrypoint. 

In the meantime, till we generate the new `kindest/node` images for v1.20 and v1.21 (which are the ones impacted by this issue), we suggest to continue utilizing the existing `nestybox/kindest/node:v1.18` and `nestybox/kindest/node:v1.19` images.

**Comment by ctalledo** [comment]
Note: even after we add support for cgroups v2 to Sysbox, using cgroups v2 requires a machine whose kernel was booted with cgroups v2. I know Fedora has made the transition to enabling cgroups v2 by default, but not sure if Ubuntu has done the same. If not enable by default, it can be easily enabled via GRUB and rebooting the host, but it's an extra step.

**Comment by ctalledo** [comment]
Sysbox v0.4.0 supports cgroups v2, so it's possible to run the latest versions of `kind` inside a Sysbox container. 

Closing.
