### ISSUE TITLE
Sysbox unable to launch on docker swarm?

### ISSUE THREAD

**Issue by jnicotra** [nestybox/sysbox#307]
Hi all, I have run into an issue that I am not sure how to solve, less-so to diagnose.

I wanted first to state my intent, and the way I've gone about it to see if you notice any glaring issues. (or even if this CAN be done)

Currently I have many (8) servers across different hosting platforms for different clients. I have noticed that individually these servers experience issues for a number of reasons, sometimes out of my control. Each server is its own VPS with SSH access, etc. 

my INTENT is to create a docker swarm on these servers across multiple platforms and then use sysbox to launch VMs across the docker swarm (to act as load-balancing and fault tolerance). I am incredibly new to Docker and the entire containerization ecosystem so please pardon any truly amateur issues here.

I noticed when trying to launch a container with Sysbox, i would get the OCI issue, but followed the directions in that guide to solve that, and it was unsuccessful.

So I guess my questions / issues are these:

1) is what I'm doing feasible?
2) Can sysbox run on docker swarm?
3) -not necessarily one to be answered here unless you want to- would I even be able to route traffic with a reverse proxy using this concept?

Thank you for the help. If there is a better place to be asking these questions, please let me know.

**Comment by rodnymolina** [comment]
@jnicotra, I'm not sure if I'm understanding your intended setup, but yes, you can use Sysbox runtime to launch system-containers orchestrated by Docker Swarm. And yes, you should be able to use these system-containers to act as reverse-proxy servers.

Please join our [slack](https://nestybox-support.slack.com/join/shared_invite/enQtOTA0NDQwMTkzMjg2LTAxNGJjYTU2ZmJkYTZjNDMwNmM4Y2YxNzZiZGJlZDM4OTc1NGUzZDFiNTM4NzM1ZTA2NDE3NzQ1ODg1YzhmNDQ#/) to continue our discussion as I want to make sure that I understand what you have in mind.

**Comment by rodnymolina** [comment]
I have addressed most of the original questions through our slack channels, where we will continue our discussion on this topic. Closing this issue now.
