### ISSUE TITLE
Any support for "Native Overlay Diff"?

### ISSUE THREAD

**Issue by uazo** [nestybox/sysbox#339]
I am experiencing a lack of support for "`Native Overlay Diff`" in an "docker in docker" configuration using `sysbox-runc`.

Inside `nestybox/ubuntu-focal-systemd-docker` container I have
```
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
```

in fact I notice an enormous slowness in the build of my images inside the container (i am using an image that derives from that).
I was wondering if it could be a problem related to some missing configuration or if it is not a feasible thing.

**Comment by ctalledo** [comment]
Hi @uazo, thanks for filing the issue and for giving Sysbox a shot.

> in fact I notice an enormous slowness in the build of my images inside the container 

That's strange, we've not seen any difference in the speed of building inner images. What container image are you building inside the Sysbox container, such that I can reproduce and debug?

**Comment by uazo** [comment]
> such that I can reproduce and debug?

sure, but unfortunately my work is still a work in progress, I am trying to create with sysbox a ci for bromite (a fork of chromium) and therefore I work with very large images, about 30gb.
the setup is a bit complex, because a self hosted custom github runner runs through sysbox, and the (docker) build is made by an action called by another action, but I try to simplify and put you in a position to try.

anyhow [here](https://github.com/uazo/bromite-buildtools/blob/master/images/github-runner/Dockerfile) is the Dockerfile, while [here](https://github.com/uazo/bromite-buildtools/tree/master/images/bromite-source) is the action and the Dockfile that have the issue.

>  we've not seen any difference in the speed of building inner images

ok, maybe I double check generating the build without dind, I wouldn't want to be wrong about the need for that function

**Comment by ctalledo** [comment]
Thanks @uazo for sharing, I'll give that Dockerfile a try a bit later today to see if I spot any problems with the build time.

**Comment by ctalledo** [comment]
Hi @uazo, I used the Dockerfile you provided and built an image both on my development machine, and inside a sysbox container (nestybox/ubuntu-focal-systemd-docker).

Here is what I see:

Build time on my dev machine: 2m 4secs
Build time inside the sysbox container: 2m 25 secs    (i.e., 10% slower)

We do expect a slight slow down inside the sysbox container due to a variety of factors (e.g., inner docker sees an extra docker network bridge, sysbox virtualizes portions of /proc and intercepts a few syscalls, etc.), but nothing major.

> in fact I notice an enormous slowness in the build of my images inside the container

I wonder why you see this and I don't. My setup is pretty simple: my development machine is Ubuntu-Focal, with an ext4 filesystem and Docker 20.10.5. 

For Sysbox, I am using Sysbox top of tree.

Could you provide info about your host machine?

Also, is this something you see consistently across different host machines?

Thanks ...

**Comment by uazo** [comment]
> Could you provide info about your host machine?

the host is an old server with ubuntu 20, 8gb ram and ssd (ext4 filesystem), latest version of docker in the host, the one you see in the dockerfile for sysbox, the only one is containerd.io=1.4.4-1 for the runc bug.
I tried it on an identical machine that I have available and actually I don't notice any problems there!

I'm very sorry I wasted your time.

> I wonder why you see this and I don't

today I will try to reinstall that machine from scratch, by heart I remember that I had upgraded from 18 to 20 on that one, maybe that's why. in the meantime I also realized that the approach I am using for generating the images is not quite correct (and therefore the performance of the build can be increased but sysbox has nothing to do with it, my fault :)
if you need any logs before resetting just let me know.

thank you so much for your support.

**Comment by ctalledo** [comment]
Hi @uazo,

> I tried it on an identical machine that I have available and actually I don't notice any problems there!

OK great, thanks for letting me know.

> I'm very sorry I wasted your time.

No worries at all, thank you for trying Sysbox and for filing the issue. Hope you are finding it useful, let us know if you hit any other issues. 

Also, feel free to join the [Sysbox slack channel](https://join.slack.com/t/nestybox-support/shared_invite/enQtOTA0NDQwMTkzMjg2LTAxNGJjYTU2ZmJkYTZjNDMwNmM4Y2YxNzZiZGJlZDM4OTc1NGUzZDFiNTM4NzM1ZTA2NDE3NzQ1ODg1YzhmNDQ), there is a community of users there that benefit from each other's experience.

Best!
