### ISSUE TITLE
Feature request: release binaries on GitHub Releases

### ISSUE THREAD

**Issue by felipecrs** [nestybox/sysbox#34]
It would be very cool if we could have the binaries (`.deb`?) uploaded in the GitHub Releases, so newcomers could easily install on their machine without having to build themselves, despite the build process is so simple.

I suggest the entire process to happen automatically under CI, such as GitHub Actions.

In case you're interested in enforcing [Semantic Versioning](https://semver.org/), I really suggest you take a look at [`semantic-release`](https://github.com/semantic-release/semantic-release).

**Comment by rodnymolina** [comment]
@felipecrs thanks for your suggestion.

Yes, we are working on it right now. As part of our next release, which we are just wrapping up, we will share the generated 'deb' packages for the distros that we are supporting. In the meantime, if you don't want to deal with the building process, you can make use of the packages we have built for our [enterprise](https://github.com/nestybox/sysbox-ee/releases) version.

In regards to CI, yes, we're planning to automate the process, but this will probably take us a bit longer.

Really appreciate your suggestions, please keep them coming. Thanks!

**Comment by felipecrs** [comment]
Thank you so much! Using the packages built for the EE solves my problem for now :).

**Comment by ctalledo** [comment]
@felipecrs : the .deb package for Sysbox has now been uploaded to the code releases. Nestybox will generate and upload these when new versions of Sysbox are tagged. 

Closing!
