### ISSUE TITLE
Building on ubuntu based distros not yet supported

### ISSUE THREAD

**Issue by ngaro** [nestybox/sysbox#397]
Although you can build from source on Ubuntu, you can't do it on Mint.
Since Mint is just Ubuntu + extras this should also work.
The same problem holds for other Ubuntu based distro's

In a couple of minutes I'll send PR that fixes this...

**Comment by ngaro** [comment]
Done : _https://github.com/nestybox/sysbox/pull/398_

**Comment by ctalledo** [comment]
Thanks @ngaro, we appreciate you enabling Sysbox builds on Linux Mint.

Closing a s PR #398 has been merged.
