### ISSUE TITLE
Docker plugins with network mode "host" fails with "container spec missing namespaces Set{network}: unknown"

### ISSUE THREAD

**Issue by derteufelqwe** [nestybox/sysbox#401]
Hello @ctalledo,

I have another issue related to Docker plugins. (Configuration is simmilar to #400).

**Expected result**
Docker managed plugins will work with network mode: "host"

**Actual result**
Docker managed plugins with network mode "host" won't start and fail with `Error response from daemon: OCI runtime create failed: error in the container spec: invalid namespace config: container spec missing namespaces Set{network}: unknown`

**Is it the fault of the network entry**
I think so. Changing the network property from `"Type": "host"` to `"Type": ""` in the plugins `config.json` resolves the issue.

_The [the official docker plugin docs](https://docs.docker.com/engine/extend/config/#example-config) contain some infos about the config.json._

**Is it sysbox-runcs fault?**
I think so. I removed "default-runtime": "sysbox-runc" from /etc/docker/daemon.json and the plugin starts just fine. Adding it again will cause the plugin to not start again.

**Relevant part of docker plugin config.json**
```
"network": {
  "type": "host"
},
```

**How to reproduce the issue**
This should be straight forward
- Download and install the latest release of sysbox-runc
- Install my docker plugin with `docker plugin install --grant-all-permissions derteufelqwe/dockermc-drivers:host`. This should return a **wanted** error like `Error response from daemon: dial unix /run/docker/plugins/<hash>/dmcdriver.sock: connect: no such file or directory`. This indicates that starting the plugin worked. The will crash tho because it's improperly configured.
- Modify your `/etc/docker/daemon.json` file to use sysbox-runc as default runtime like this
```
...
 "runtimes": {
    "sysbox-runc": {
        "path": "/usr/bin/sysbox-runc"
    }
},
"default-runtime": "sysbox-runc",
...
```
- Restart the docker daemon
- Try to enable the plugin with `docker plugin enable derteufelqwe/dockermc-drivers:host`
- This will fail with the mentioned error

_Note:_
This is not the fault of my plugin. [Weave works weave.net plugin](https://www.weave.works/docs/net/latest/install/plugin/plugin-v2/) (`docker plugin install weaveworks/net-plugin:latest`) has the same issue.

**Comment by ctalledo** [comment]
Hi @derteufelqwe, thanks for opening the issue.

Sysbox does not support running containers with `--network=host`. The reason being that this breaks isolation between the container and the host, and strong container isolation is one of the key drivers behind Sysbox. At a technical level, this arises from the fact that Sysbox containers always run with the Linux user-namespace enabled, and that prevents sharing the network namespace with the host.

See here for a list of similar limitations: https://github.com/nestybox/sysbox/blob/master/docs/user-guide/limitations.md

If your plugin absolutely needs to share the host network with the host, I am afraid that plugin will need to run with the default runc runtime.

Is this a viable solution?

**Comment by derteufelqwe** [comment]
Oh, I didn't see that. I will find a workaround then.
