### ISSUE TITLE
Bug: Sysbox v0.2.1 Error response from daemon on Ubuntu 18.04

### ISSUE THREAD

**Issue by max55** [nestybox/sysbox#41]
after building from source and running the given example

`docker run --runtime=sysbox-runc -it debian`

i get the following error:

```
docker: Error response from daemon: OCI runtime create failed: failed to register with sysbox-mgr: failed to invoke Register via grpc: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/sysbox/sysmgr.sock: connect: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled 
```

**Comment by rodnymolina** [comment]
@max55, did you find the issue, right? Looks like sysbox daemons may not be running in your setup. If you are building from sources you can make use of the 'scr/sysbox' script to launch sysbox processes.

Let us know if any question.

**Comment by max55** [comment]
Thanks for the quick reply. I somehow solved the problem by installing the deb-package. (I didn't spot that before)

**Comment by rodnymolina** [comment]
Thanks @max55. Would be great if you could copy-paste the set of instructions you executed to reproduce the issue you saw ... we may be missing something here 😔
