### ISSUE TITLE
mkdirall var/lib/docker with mode 755 failed

### ISSUE THREAD

**Issue by mjafari98** [nestybox/sysbox#412]
Why is this happening?

```bash
➜  ~ docker run --runtime=sysbox-runc --rm -it alpine:3.14 /bin/bash

docker: Error response from daemon: OCI runtime create failed: container_linux.go:393: starting container process caused: process_linux.go:607: container init caused: rootfs_linux.go:68: setting up rootfs mounts caused: mkdirall var/lib/docker with mode 755 failed: mkdir var/lib/docker: permission denied: unknown.
```

It used to work properly until today! Reinstallation of _sysbox-ce_ didn't help.

```bash
➜  ~ uname -rvo  
5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 GNU/Linux

➜  ~ docker version
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:29 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

➜  ~ cat /etc/docker/daemon.json
{
    "runtimes": {
        "sysbox-runc": {
            "path": "/usr/bin/sysbox-runc"
        }
    },
    "bip": "172.20.0.1/16",
    "default-address-pools": [
        {
            "base": "172.25.0.0/16",
            "size": 24
        }
    ]
}

```

**Comment by rodnymolina** [comment]
@mjafari98, thanks for reporting this issue. I'm unable to reproduce it though.

Can you please indicate which sysbox release are you currently using (`systemctl status sysbox -n20`)?

Also, do you remember changing / updating any relevant system component (such as Docker) that may help us narrow down and reproduce this issue?

```
rmolina@dev-vm1:~$ uname -r
5.11.0-37-generic

rmolina@dev-vm1:~$ docker run --runtime=sysbox-runc --rm -it alpine:3.14 /bin/sh
/ #
```

**Comment by mjafari98** [comment]
> @mjafari98, thanks for reporting this issue. I'm unable to reproduce it though.
> 
> Can you please indicate which sysbox release are you currently using (`sudo systemctl status sysbox -n20`)?
> 
> Also, do you remember changing / updating any relevant system component (such as Docker) that may help us narrow down and reproduce this issue?
> 
> ```
> rmolina@dev-vm1:~$ uname -r
> 5.11.0-37-generic
> 
> rmolina@dev-vm1:~$ docker run --runtime=sysbox-runc --rm -it alpine:3.14 /bin/sh
> / #
> ```

I was using the latest version `v0.4.1`. I tried reinstalling _synbox_ but it didn't resolve the issue. I backed up all of my docker images and completely purged my docker engine and all of its packages and related packages also. After a reboot and installing docker again, I tried to install _synbox_ again and the problem was gone.

So, I don't know how to reproduce the error, after all. 
Thanks for the answers.

**Comment by mjafari98** [comment]
> Hi @mjafari98 ,
> 
> > I backed up all of my docker images and completely purged my docker engine and all of its packages and related packages also. After a reboot and installing docker again, I tried to install synbox again and the problem was gone.
> 
> I see; it must be related to the permissions in the `/var/lib/docker` directory then; they must have gotten fixed when you re-installed Docker from scratch.
> 
> Just to confirm, you re-installed Docker 20.10.9 correct?

Yes. I am suspicious to `ncdu`! The problem appeared once I ran `ncdu` on `/var/lib/docker` directory. I didn't double-check that though.
