### ISSUE TITLE
Kubelet is not restarted after installing sysbox with Ubuntu20.04 on EKS

### ISSUE THREAD

**Issue by anthonysuterag** [nestybox/sysbox#430]
Hello, I am trying to install `sysbox` on one of my EKS unmanaged nodegroups. After provisioning the nodegroup, I followed this documentation https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#installation-of-sysbox for installing `sysbox`. 

However, after the DS pod finished installing, my node is stuck in `NotReady` state. After some effort of debugging, I figured out that the `kubelet` was inactive and I had to restart it manually. 

Command for checking kubelet status: `snap services kubelet-eks`
Command for starting the kubelet: `snap restart kubelet-eks.daemon`

Once, I have done that, I see the node becomes ready and I can run my sysbox pod on that node. 

Below is some additional information.
EKS version: `v1.20.7`
OS: `Ubuntu20.04`
sysbox-deploy-k8s image version: `v0.4.1`

My current assumption is the latest EKS Ubuntu AMI installs `kubelet` via `snap`, so the script needs to be adjusted to restart `kubelet` via `snap` as well.

**Comment by rodnymolina** [comment]
@anthonysuterag, thanks for filing this one up! And great to hear that you found a workaround yourself ...

I'm not sure what may have happened here as we are fully aware of AWS' kubelet peculiarities (snap-based) and we have tested this setup accordingly.

In order for us to quickly reproduce this one, can you please let us know how did you created your cluster? Did you use  `eksctl`, or `kops`, or AWS's GUI, etc?

**Comment by anthonysuterag** [comment]
Hi @rodnymolina, thanks for the quick response ! 

I see, I guess I missed that when digging in the installation script. 

I use `eksctl` (`v0.58.0`) to provision the cluster.

**Comment by rodnymolina** [comment]
@anthonysuterag, just to let you know that I was able to reproduce the problem and that a fix should be available later today (Friday).

**Comment by rodnymolina** [comment]
@anthonysuterag, fix has been merged. Please go through our installation process once again and let us know if any other question. Will close this issue now.

Btw, you were right, there was a problem with our snap-based kubelet restart instruction, which is interesting coz this same instruction has been working fine for us for quite a while, so I suspect that something must have been changed on EKS side ... perhaps the snapd package version or alike ...

Thanks for letting us now!
