### ISSUE TITLE
centos8 sysbox-fs.log error msg="fusermount: exec: \"fusermount\": executable file not found in $PATH"

### ISSUE THREAD

**Issue by kenzero3** [nestybox/sysbox#448]
centos8 5.15.8-1.el8.elrepo.x86_64

sysbox-fs.log: 
error msg="fusermount: exec: \"fusermount\": executable file not found in $PATH"

sysbox-mgr.log:
time="2021-12-20 09:33:04" level=info msg="registered new container a1563ee6dce6"
time="2021-12-20 09:33:24" level=info msg="unregistered container a1563ee6dce6"

docker log:
Error response from daemon: OCI runtime create failed: failed to pre-register with sysbox-fs: failed to pre-register container with sysbox-fs: rpc error: code = DeadlineExceeded desc = context deadline exceeded: unknown. 

Please help me！

Tell me how to solve this error.

**Comment by ctalledo** [comment]
> error msg="fusermount: exec: "fusermount": executable file not found in $PATH"

FYI: Sysbox requires the fusermount package be installed on the host.

**Comment by kenzero3** [comment]
> > error msg="fusermount: exec: "fusermount": executable file not found in $PATH"
> 
> FYI: Sysbox requires the fusermount package be installed on the host.

This solution is very useful, thank you so much
