### ISSUE TITLE
[Documentation] Shiftfs no branch for kernel 5.8

### ISSUE THREAD

**Issue by AugustasV** [nestybox/sysbox#459]
On official git repo there is no version for kernel 5.8 of Shiftfs
![image](https://user-images.githubusercontent.com/7377334/151055761-92dbc636-db83-4f3d-83ea-1fb4af1a66c6.png)
So instructions on documentation is wrong in that sense:
https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-package.md#installing-shiftfs

What version I should change in docs, in case that branch for kerne l5.8 is not available?
Or find some mirror somewhere for kernel 5.8?

**Comment by ctalledo** [comment]
Hi @AugustasV , apologies for the super late reply, I totally dropped the ball on responding.

Though it's not super obvious, the shiftfs-dkms repo does indicate that for 5.8 kernels, you should use branch 5.10. See [here](https://github.com/toby63/shiftfs-dkms#overview-of-branchesversions).

Closing the PR.

**Comment by AugustasV** [comment]
@ctalledo Ok good to know! That's why install steps have to be updated in docs. Created PR.
