### ISSUE TITLE
bug: EACCES on some listxattr calls from within a sysbox container

### ISSUE THREAD

**Issue by deansheather** [nestybox/sysbox#460]
- Release: untagged/master since 2c0cfb3531f9f03c8267fb9bbd6b256b3f187519
- Host: Ubuntu 20.04 `5.11.0-1028-gcp` and `5.4.0-1051-gke`
- Sysbox compiled with `make IMAGE_BASE_DISTRO=ubuntu IMAGE_BASE_RELEASE=bionic sysbox` and using shiftfs.

#### Description:
Doing a `listxattr` syscall (e.g. via `getfattr`) as a non-root user on a file in a dir owned by the current user with perms `rwx------` returns EACCES when it should succeed.

```console
coder@dean-c:/tmp/z/tmp0e0jaca_$ ls -alh
total 4.0K
drwx------ 2 coder coder 60 Jan 24 17:54 .
drwxrwxrwt 3 root  root  60 Jan 24 17:54 ..
-rw-rw-r-- 1 coder coder  3 Jan 24 17:54 x
coder@dean-c:/tmp/z/tmp0e0jaca_$ getfattr x
getfattr: x: Permission denied
```

However, running it on a file on a dir owned by the current non-root user with perms `rwxr-xr-x` does not cause the bug.

The bug appears to come from commit 2c0cfb3531f9f03c8267fb9bbd6b256b3f187519.

#### Reproduction steps:
On the current master version of sysbox 3a73a4bcdf5dcf1bb2c6357f8ba6a5cdc2c88b11:
```console
$ docker run --runtime=sysbox-runc --rm -it alpine:latest
/ # apk add --no-cache attr strace
...
/ # adduser dean
...
/ # su - dean
c2c9904d7202:~$ mkdir /tmp/test
c2c9904d7202:~$ cd /tmp/test
c2c9904d7202:/tmp/test$ touch x
c2c9904d7202:/tmp/test$ chmod 700 /tmp/test
c2c9904d7202:/tmp/test$ ls -alh
total 8K
drwx------    2 dean     dean        4.0K Jan 26 02:11 .
drwxrwxrwt    1 root     root        4.0K Jan 26 02:11 ..
-rw-r--r--    1 dean     dean           0 Jan 26 02:11 x
c2c9904d7202:/tmp/test$ getfattr x
getfattr: x: Permission denied
```

Running `strace getfattr x` in the same environment reveals that the `listxattr` syscall is failing with EACCES.
```
listxattr("x", NULL, 0) = -1 EACCES (Permission denied)
```

Running the same reproduction steps in a non-sysbox container lets the `getfattr` call succeed.

**Comment by rodnymolina** [comment]
Will take a look.

**Comment by rodnymolina** [comment]
@deansheather, this one should have been fixed as part of this [commit](https://github.com/nestybox/sysbox-fs/commit/ecd6ee723bf9a5d8b7a070d52753a85cde4e79c0). Please reopen this issue if that's not the case.
