### ISSUE TITLE
dind-nvidia

### ISSUE THREAD

**Issue by lisenux** [nestybox/sysbox#470]
How to use the nvidia  inside the container

**Comment by rodnymolina** [comment]
@lisenux, would [this](https://github.com/nestybox/sysbox/issues/50) one meet your requirements?

If that's the case, we expect to be able to start working on this feature very soon. Could you please tell us a little bit about the use-case that you have in mind?

Thanks.

**Comment by ctalledo** [comment]
Duplicate of issue #50.
