### ISSUE TITLE
Installation on Rocky Linux

### ISSUE THREAD

**Issue by carlfischerjba** [nestybox/sysbox#471]
Rocky Linux 8 is very similar to CentOS 8 but only CentOS 8 is supported by Sysbox. Is there a way to compile Sysbox on Rocky Linux (or other similar distributions)?

**Comment by rodnymolina** [comment]
@carlfischerjba, we haven't perceived much interest from Sysbox community to support Rocky-Linux. In the distro compatibility front we are currently focusing on supporting more mainstream distros such as Redhat, and trying to reach feature-parity with others like Debian and Fedora.

Could you please explain why is this important for you, and what's the use-case that you have in mind?

Also, if you have the cycles/interest you can try to do this by your own. Just take a look at any of the [existing](https://github.com/nestybox/sysbox/tree/master/tests) `test/Dockerfiles.<distro-release>` files and create an equivalent one for rocky-linux.

**Comment by rodnymolina** [comment]
@carlfischerjba, you may find [this](https://github.com/nestybox/sysbox/pull/477) recent PR merged by @roussidis interesting for you desire to build Sysbox in RockyLinux. In that case he was addressing AlmaLinux distro, but being this one so relatively close to RockyLinux, I suspect that you may just need to do minor adjustments to have [this](https://github.com/nestybox/sysbox/blob/master/tests/Dockerfile.almalinux-8) Dockerfile able to build Sysbox for you on a RockyLinux machine.

**Comment by carlfischerjba** [comment]
Thanks. That looks really useful. 

I was setting up GitLab CI runners in Docker recently and it looked like Sysbox might provide a good solution to some of the security concerns around running privileged Docker containers. Your [blog post](https://blog.nestybox.com/2020/10/21/gitlab-dind.html) was quite appealing. Unfortunately our machines are mostly CentOS-based, moving to RockyLinux, which has made it harder to trial.

**Comment by rodnymolina** [comment]
@carlfischerjba, let us know if you need help adjusting the AlmaLinux Dockerfile to be able to build/run Sysbox on RockyLinux.

**Comment by roussidis** [comment]
@carlfischerjba it should be fairly easy if you modify the names accordingly. I am glad to help if anything comes up.
