### ISSUE TITLE
Publish docker images to GitHub Container Registry

### ISSUE THREAD

**Issue by felipecrs** [nestybox/sysbox#49]
[Since Docker Hub has imposed pull rate limits](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/), I'm not able to pull anything from there from my company anymore. So I have to manually mirror the image to another registry that I can access.

This is a suggestion for you to push the Docker images not only to Docker Hub, but also to the [recently introduced GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/).

It would be awesome to be able to:

```sh-session
$ docker pull ghcr.io/nestybox/ubuntu-focal-systemd-docker
```

I strongly suggest using GitHub Actions to automate it :).

**Comment by felipecrs** [comment]
Thank you so much!

If you find it useful, you may take a look at how I just started to push one of my images to ghcr.io, in this PR: https://github.com/felipecrs/jenkins-agent-dind/pull/14.

It's extremely simple :-).

**Comment by rodnymolina** [comment]
@felipecrs, thanks for pointing this out and also for your suggestion. We will definitely take a look at this.

**Comment by rodnymolina** [comment]
@felipecrs, i finished uploading our docker images to github's container-registry, please give it a try when have a chance (e.g. "docker pull ghcr.io/nestybox/ubuntu-focal-systemd-docker").

Also, as suggested, i went ahead and created a github-action to automate the build&push process for both Dockerhub and Github registries.

Let us know if have any other suggestion. Thanks.

**Comment by felipecrs** [comment]
@rodnymolina it works very well! :D
