### ISSUE TITLE
Issues found during sysbox build from source on Fedora 35

### ISSUE THREAD

**Issue by fhaefemeier** [nestybox/sysbox#513]
I build sysbox from source following the [guide](https://github.com/nestybox/sysbox/blob/master/docs/developers-guide/build.md) on Fedora 35. I was running into the following minor issues:

- No Dockerfile for Fedora 35 in `tests` directory
_Mitigation_: I copied Fedora 34 dockerfile, named it `Dockerfile.fedora-35` and changed base image to `fedora:35`
- Missing `lsb_release`. Documentation does not mention it as a prerequisite on host
_Mitigation_: I changed Makefile and set the value hard-coded to get sysbox compiled
Question: is it a strong requirement to install `lsb_release` or could it be replaced?
- Makefile does not respect multiple `default` gateway entries returned by `ip route show`
_Mitigation_: changed the line into `$(shell ip route show default | head -1 | awk '/default via/ {print $$5}')`
- Fedora 35 changed the behaviour to setup PATH variable. `.local/bin` is only add to `PATH` if it is a login shell. Therefor `protobuf` was not found.
_Mitigation_: I changed `bash -c` into `bash -ic`

I know, some of my mitigation are not the correct or the best way, but it was a pragmatic way for me to get the compilation to work. Whether the build is working, will be tested in the next days.

**Comment by ctalledo** [comment]
Thanks @fhaefemeier for the info!

> Question: is it a strong requirement to install lsb_release or could it be replaced?

It probably could be replaced by looking at `/etc/os-release` directly. Do you know if this dependency coming from the Sysbox Makefile or somewhere else?

> Whether the build is working, will be tested in the next days.

Sounds good, let us know of any other issues you find in the process.

**Comment by fhaefemeier** [comment]
> > Question: is it a strong requirement to install lsb_release or could it be replaced?
> 
> It probably could be replaced by looking at `/etc/os-release` directly. Do you know if this dependency coming from the Sysbox Makefile or somewhere else?
> 
Yes it is in the Makefile
```
diff --git a/Makefile b/Makefile
index de63519..592b932 100644
--- a/Makefile
+++ b/Makefile
@@ -84,7 +84,8 @@ else
 INSTALL_DIR := ${DESTDIR}
 endif
 
-IMAGE_BASE_DISTRO := $(shell lsb_release -is | tr '[:upper:]' '[:lower:]')
+#IMAGE_BASE_DISTRO := $(shell lsb_release -is | tr '[:upper:]' '[:lower:]')
+IMAGE_BASE_DISTRO := fedora
 
 # Host kernel info
 KERNEL_REL := $(shell uname -r)
@@ -94,7 +95,8 @@ export KERNEL_REL
 
 # Sysbox image-generation globals utilized during the sysbox's building and testing process.
 ifeq ($(IMAGE_BASE_DISTRO),$(filter $(IMAGE_BASE_DISTRO),centos fedora redhat almalinux rocky))
-       IMAGE_BASE_RELEASE := $(shell lsb_release -ds | tr -dc '0-9.' | cut -d'.' -f1)
+       # IMAGE_BASE_RELEASE := $(shell lsb_release -ds | tr -dc '0-9.' | cut -d'.' -f1)
+       IMAGE_BASE_RELEASE := 35
        KERNEL_HEADERS := kernels/$(KERNEL_REL)
 else
        IMAGE_BASE_RELEASE := $(shell lsb_release -cs)
```

**Comment by ctalledo** [comment]
This issue has been fixed via this PR: https://github.com/nestybox/sysbox/pull/520

Closing.
