### ISSUE TITLE
Sysbox on Kubernetes Cluster - Which pod security policy capabilities are needed to run docker-in-docker dockerd? 

### ISSUE THREAD

**Issue by FFock** [nestybox/sysbox#523]
I am currently traing to get sysbox running in a Rancher 2.6 downstream cluster with k8s 1.21.10 behind a Internet HTTPs proxy following the instructions on https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md using Ubuntu 20.04 (latest). The Internet proxy issue was (hopefully) solved by https://github.com/nestybox/sysbox/issues/522

Now I am struggeling finding the right capabilities for a "docker-in-docker" pod security policy. So far, I know that NET_ADMIN is required to be able to access iptables.

But the next issue is:
`failed to start daemon: Error initializing network controller: error obtaining controller instance: Enabling IP forwarding failed: open /proc/sys/net/ipv4/ip_forward: read-only file system`

As I did not find any documentation on pod security capabilities on https://github.com/nestybox/sysbox/blob/master/docs I am asking here:

**Does someone has a list of absolutely necessary capabilitiesto run docker-in-docker and kubernetes in container on a sysbox enabled k8s node?**

**Comment by FFock** [comment]
I forgot to mention that I am trying to deploy a test docker image from sysbox:
`nestybox/ubuntu-bionic-systemd-docker`

It seems that the capabilities are not the problem, because ip-forwarding is disabled in the ubuntu of the container (on the host node it is enabled of course and /proc is writable there too!):

```
$ cat /proc/sys/net/ipv4/ip_forward
0
$ mount
...
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
...
```
I learned that /proc is mounted read-only in any non-privileged container. 
This article provides a workaround for it: https://github.com/kubernetes/kubernetes/issues/62942
I am now trying to find out, how to enable forwarding in the `nestybox/ubuntu-bionic-systemd-docker` pod using a modified pod security policy...

**Comment by rodnymolina** [comment]
@FFock, in regards to your first question about the "necessary capabilities", please be aware that Sysbox runtime allows all capabilities to the container's init process when this one is owned by the container's 'root' user, and disables them all for non-root users. You can verify it by doing something like this:

<-- Init process owned by 'root':

```
$ docker run --runtime=sysbox-runc -it alpine:latest
/ # grep -i cap /proc/self/status
CapInh: 0000003fffffffff
CapPrm: 0000003fffffffff
CapEff: 0000003fffffffff
CapBnd: 0000003fffffffff
CapAmb: 0000003fffffffff
```

<-- Init process owned by non-root:

```
admin@test-1:~$ egrep -i "cap" /proc/self/status
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
```

Please check this [doc](https://github.com/nestybox/sysbox/blob/cf2cfe0a199c5eb35beebb114c9c5da11606b618/docs/user-guide/design.md#process-capabilities) for more details.
 
In regards to your second question, I believe that the pod that you are looking at must be instantiated by a runtime other than Sysbox. I'm saying this because Sysbox always mounts `/proc/sys` in RW mode, so you shouldn't need to touch your default pod-security-policies to accomplish this. Also, `/proc/sys/net/ipv4/ip_forward` sysctl should be turned on by default:

```
admin@test-1:~$ cat /proc/sys/net/ipv4/ip_forward
1
```

Please make sure that your pod spec is adding the fields required for Sysbox to operate as expected: https://github.com/nestybox/sysbox/blob/master/docs/user-guide/deploy.md#deploying-pods-with-kubernetes--sysbox

Hope this helps.

**Comment by FFock** [comment]
You are right, the container did not run with the `sysbox-runc`. I changed it but then I get:
`Failed to create pod sandbox: rpc error: code = Unknown desc = container create failed: time="2022-04-02T06:23:59Z" level=error msg="container_linux.go:393: starting container process caused: process_linux.go:607: container init caused: rootfs_linux.go:68: setting up rootfs mounts caused: rootfs_linux.go:1104: mounting \"sysfs\" to rootfs \"/var/lib/sysbox/shiftfs/433d4ac1-4d2e-4264-a4a5-5e399b012a03\" at \"sys\" caused: operation not permitted"`

I am now trying to find the reason for that...

**Comment by rodnymolina** [comment]
Do you happen to have `/sys` or `/sys/fs/cgroup` mounted as RO in this host? If that's the case, our daemonset should have remounted these nodes as RW automatically, but wondering if something failed there...

To confirm the above, please obtain `findmnt` (on the affected host) and dump its output here. If either one of these appears as RO, please remount it manually as RW by doing the following and then try to create a sysbox-pod again:

```
mount -o rw,remount /sys
```

or 

```
mount -o rw,remount /sys/fs/cgroup
```

**Comment by FFock** [comment]
Ok, totally my fault not reading the manual carefully enough. What was missing is specifying the usernamespace mode with (see https://github.com/nestybox/sysbox/issues/67 for background info): 

**io.kubernetes.cri-o.userns-mode: "auto:size=65536"**

and the initial error by not specifying the sysbox runtime:

**runtimeClassName: sysbox-runc**

in my deployment yaml as shown in detail at: https://github.com/nestybox/sysbox/blob/master/docs/user-guide/deploy.md#deploying-pods-with-kubernetes--sysbox

Now it works as expected without given any additonal capabilities. Thanks for the great help und good documenation (if you know what you are doing ;-) )

**Comment by rodnymolina** [comment]
Yep, that's another explanation for what you saw above ;-)

Let us know if face any other issues. Btw, I would suggest joining our [slack](https://nestybox-support.slack.com/join/shared_invite/enQtOTA0NDQwMTkzMjg2LTAxNGJjYTU2ZmJkYTZjNDMwNmM4Y2YxNzZiZGJlZDM4OTc1NGUzZDFiNTM4NzM1ZTA2NDE3NzQ1ODg1YzhmNDQ#/) if want to have more direct communication with us and our community.
