### ISSUE TITLE
Sysbox version 5.2 deb package install fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by DataSymphony** [nestybox/sysbox#561]
Hi

I am trying to update my Sysbox version from 5.0 to 5.2 but the deb package install fails. Has anyone else experienced an installation problem?

Thanks

**Comment by rodnymolina** [comment]
@DataSymphony, please provide installation log errors.

**Comment by DataSymphony** [comment]
The issue turned out to be related to running docker containers that needed to be stopped first before installing sysbox.
