### ISSUE TITLE
kubelet-config-helper.sh stops containerd on GKE

### ISSUE THREAD

**Issue by RamyAllam** [nestybox/sysbox#562]
I'm using Sysbox on GKE - ubuntu_containerd image and it is installed using [sysbox-deploy-k8s daemonset](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md)

It looks like the `kubelet-config-helper.sh` script is stopping Containerd service using `stop_containerd` in `do_config_kubelet_snap` function.

The issue with that is `ubuntu_containerd` image in GKE is having [Docker installed by default](https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd#building_container_images_with_containerd) and Docker requires `containerd` up and running, otherwise, it floods `journalctl` with the below errors
```
Jun 13 13:08:22 gke-worker-01-pool-1-abc-j1ps dockerd[2627]: time="2022-06-13T13:08:22.152347665Z" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\"" module=libcontainerd namespace=plugins.moby
Jun 13 13:09:48 gke-worker-01-pool-1-abc-j1ps dockerd[2627]: time="2022-06-13T13:09:48.625736825Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Jun 13 13:09:48 gke-worker-01-pool-1-abc-j1ps dockerd[2627]: time="2022-06-13T13:09:48.626236765Z" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout\"" module=libcontainerd namespace=moby
```

Also the `kubelet-config-helper.sh` script is stopping `containerd` service only without disabling it so the `containerd` is restarted when the GKE worker node is rebooted.

I'm not sure about the story behind it but I'm concerned that GKE at some points marks the node as unhealthy because of those continuous errors.  And if stopping `containerd` service is inevitable, should we stop docker service as well and disable them both? This might be an issue though for users that use Docker on the worker node for building images.

Thanks,

**Comment by ctalledo** [comment]
Hi @RamyAllam,

Thanks for giving Sysbox a shot in your GKE cluster.

Some background:

sysbox-deploy-k8s will install CRI-O on the K8s node and reconfigure the Kubelet to use CRI-O. It will also stop all containers on the existing runtime (e.g., containerd). The result (if things are working as expected) is that containerd should be quiesced, while CRI-O launches all the pods on the node.

Question:

1) Can you tell us how to repro the problem? Last I tried on GKE a few days ago I did not see any issues.

Regarding:

> Also the kubelet-config-helper.sh script is stopping containerd service only without disabling it so the containerd is restarted when the GKE worker node is rebooted.

That's correct; we should probably consider disabling it too; I don't believe we targeted the scenario where the GKE node would reboot though (because under normal circumstances it shouldn't).

>  but I'm concerned that GKE at some points marks the node as unhealthy because of those continuous errors

Yes that would be a problem; however if things are working as we expect, there should not be errors from Docker/Containerd on the node and thus the node should remain healthy.

**Comment by rodnymolina** [comment]
Same here, I don't remember seeing this behavior of dockerd being kept active trying to reach containerd, especially since we are talking about a containerd-only setup. But yes, I do see the issue that @RamyAllam reported.

**Comment by rodnymolina** [comment]
@RamyAllam, which k8s release are you installing in GKE? 1.23.5-gke.1501 or 1.22 one?

**Comment by RamyAllam** [comment]
Heey @ctalledo Thanks for your response

> Can you tell us how to repro the problem? Last I tried on GKE a few days ago I did not see any issues.

Yeah sure, it's as follows
- Create a GKE cluster Ubuntu with containerd (ubuntu_containerd) image
- Label the nodes sysbox-install=yes
- Run the manifest file: sysbox-ee-install.yaml
- SSH to any of the GKE worker nodes and execute `journalctl -t dockerd -f` you will notice Docker is trying to connect to Containerd and produces errors.

> @RamyAllam, which k8s release are you installing in GKE? 1.23.5-gke.1501 or 1.22 one?

Heey @rodnymolina 
- The cluster version is: 1.22.8-gke.201

Please let me know if you need any additional information, or want me to test a different version.  Thanks,

**Comment by rodnymolina** [comment]
@RamyAllam, the fix went into the latest sysbox-k8s-deploy image, please try it when have a chance and let us know if any issue.

Btw, we decided to leave containerd running during sysbox-k8s-deploy installation, so that should address the (very good) questions you raised.

**Comment by rodnymolina** [comment]
Closing.
