### ISSUE TITLE
Support for k8s version 1.24/1.25 ?

### ISSUE THREAD

**Issue by andrei-nefeli** [nestybox/sysbox#612]
Hello, will sysbox be updated to 1.24/1.25 ? I'm using GKE

because 1.23 end of life soon: 2023-02-28

**Comment by ctalledo** [comment]
Hi @andrei-nefeli, thanks for asking; plan is to add support for v1.24/v1.25 in January 2023.

**Comment by zeus** [comment]
Hi! Any updates?

**Comment by rodnymolina** [comment]
@zeus, no update, we're working on it.

**Comment by DekusDenial** [comment]
just tapping in, 1.25 is gonna land soon, likely early March

**Comment by rodnymolina** [comment]
@DekusDenial, @zeus, @andrei-nefeli, we are still in the pre-release stage, but could you please give this image a try and let me know how it goes? This one is expected to support k8s/crio v1.22-1.26.

To point to it, you will need to update our install/uninstall [manifests](https://github.com/nestybox/sysbox/tree/master/sysbox-k8s-manifests): `ghcr.io/nestybox/sysbox-deploy-k8s:rodny-dev`.

**Comment by DekusDenial** [comment]
> @DekusDenial, @zeus, @andrei-nefeli, we are still in the pre-release stage, but could you please give this image a try and let me know how it goes? This one is expected to support k8s/crio v1.22-1.26.
> 
> To point to it, you will need to update our install/uninstall [manifests](https://github.com/nestybox/sysbox/tree/master/sysbox-k8s-manifests) to `ghcr.io/nestybox/sysbox-deploy-k8s:rodny-dev`.

will give it a try on EKS 1.24, thanks

**Comment by zeus** [comment]
> @DekusDenial, @zeus, @andrei-nefeli, we are still in the pre-release stage, but could you please give this image a try and let me know how it goes? This one is expected to support k8s/crio v1.22-1.26.
> 
> To point to it, you will need to update our install/uninstall [manifests](https://github.com/nestybox/sysbox/tree/master/sysbox-k8s-manifests) to `ghcr.io/nestybox/sysbox-deploy-k8s:rodny-dev`.

Failed on bare metal + RKE2 (v1.24.8+rke2r1)

Pod failed to start with:
```
Detected Kubernetes version v1.24
Deploying Kubelet config agent on the host ...

Running Kubelet config agent on the host (will restart Kubelet and temporary bring down all pods on this node for ~1 min) ...
Job for kubelet-config-helper.service failed because the control process exited with error code. See "systemctl status kubelet-config-helper.service" and "journalctl -xe" for details.
```

```
From system logs
Feb 09 23:05:43 gamma sh[3634524]: + kubelet_rke_deployment
Feb 09 23:05:43 gamma sh[3634524]: + command -v docker
Feb 09 23:05:43 gamma sh[3634767]: + docker inspect '--format={{.Config.Labels}}' kubelet
Feb 09 23:05:43 gamma sh[3634768]: + egrep -q rke.container.name:kubelet
Feb 09 23:05:43 gamma sh[3634767]: Error: No such object: kubelet
Feb 09 23:05:43 gamma sh[3634524]: + kubelet_rke2_deployment
Feb 09 23:05:43 gamma sh[3634524]: + systemctl is-active --quiet rke2-agent
Feb 09 23:05:43 gamma sh[3634524]: + false
Feb 09 23:05:43 gamma sh[3634524]: + kubelet_docker_systemd_deployment
Feb 09 23:05:43 gamma sh[3634524]: + command -v docker
Feb 09 23:05:43 gamma sh[3634810]: + systemctl show kubelet.service
Feb 09 23:05:43 gamma sh[3634811]: + egrep -q '^ExecStart.*=docker run'
Feb 09 23:05:43 gamma sh[3634524]: + return 1
Feb 09 23:05:43 gamma sh[3634524]: + do_config_kubelet
Feb 09 23:05:43 gamma sh[3634524]: + echo 'Detected systemd-managed host-based kubelet deployment on host.'
Feb 09 23:05:43 gamma sh[3634524]: Detected systemd-managed host-based kubelet deployment on host.
Feb 09 23:05:43 gamma sh[3634812]: ++ get_kubelet_bin
Feb 09 23:05:43 gamma sh[3634814]: +++ systemctl show kubelet
Feb 09 23:05:43 gamma sh[3634815]: +++ grep ExecStart=
Feb 09 23:05:43 gamma sh[3634816]: +++ cut -d ';' -f1
Feb 09 23:05:43 gamma sh[3634812]: ++ local tmp=
Feb 09 23:05:43 gamma sh[3634812]: ++ tmp=
Feb 09 23:05:43 gamma sh[3634821]: ++ echo ''
Feb 09 23:05:43 gamma sh[3634822]: ++ xargs
Feb 09 23:05:43 gamma sh[3634524]: + kubelet_bin=
Feb 09 23:05:43 gamma sh[3634524]: + '[' -z '' ']'
Feb 09 23:05:43 gamma sh[3634524]: + die 'Kubelet binary not identified.'
Feb 09 23:05:43 gamma sh[3634524]: + msg='Kubelet binary not identified.'
Feb 09 23:05:43 gamma sh[3634524]: + echo 'ERROR: Kubelet binary not identified.'
Feb 09 23:05:43 gamma sh[3634524]: ERROR: Kubelet binary not identified.
Feb 09 23:05:43 gamma sh[3634524]: + exit 1
Feb 09 23:05:43 gamma systemd[1]: kubelet-config-helper.service: Main process exited, code=exited, status=1/FAILURE

```

**Comment by rodnymolina** [comment]
Thanks @zeus, was not expecting that, will check it out and have it fixed before our upcoming release.

**Comment by aldcons** [comment]
> @DekusDenial, @zeus, @andrei-nefeli, we are still in the pre-release stage, but could you please give this image a try and let me know how it goes? This one is expected to support k8s/crio v1.22-1.26.
> 
> To point to it, you will need to update our install/uninstall [manifests](https://github.com/nestybox/sysbox/tree/master/sysbox-k8s-manifests) to `ghcr.io/nestybox/sysbox-deploy-k8s:rodny-dev`.

I have also started using this in EKS and so far is good. Is there a rough estimate for a release date? I would like to be on a fixed known version.

**Comment by rodnymolina** [comment]
@aldcons, thanks for giving this test image a try.

In regards to the new release's ETA, we are taking some extra time to fix important issues and add some key features. We expect to be able to generate a new release by the end of next week or the week after.

**Comment by aldcons** [comment]
Just my luck - I tried to use arm64 with this image. Obviously I'm getting an error :
"exec /use/bin/bash: exec format error" from the pod. 

Is there a workaround or an arm64 dev image lying around 😁

Thanks

**Comment by rodnymolina** [comment]
@aldcons, you're right, the dev-test image that we provided is only for amd64, sorry for that. We expect to have a final release in the next few days anyways.

**Comment by aldcons** [comment]
> 

Brilliant, thank you. 

Can't wait for the release!

**Comment by jonmcewen** [comment]
1.23 is EOL today

**Comment by NovemberZulu** [comment]
Hello, are there any news about the release? I tried `ghcr.io/nestybox/sysbox-deploy-k8s:rodny-dev` in Azure AKS v1.25.4, but all pods on the node die with an event along
```
Failed to create pod sandbox: rpc error: code = Unknown desc = creating pod sandbox with name "k8s_csi-azuredisk-node-p4mv4_kube-system_75863384-c3eb-4ebe-b291-172071effecc_0": empty trailing digest or ID in "@": invalid reference
```
Thanks!

**Comment by ctalledo** [comment]
@rodnymolina is working on the release right now, hopefully will be ready by next week.

Thanks @NovemberZulu for reporting the issue with Azure AKS v1.25, looks like the sysbox-deploy-k8s daemonset needs an adjustment to support that.

**Comment by ctalledo** [comment]
> Hello, how is the release going? Thanks!

Apologies for the delay but it has been a bit more difficult than expected; @rodnymolina is working on it and we are working hard to deliver it before end of the month.

**Comment by NovemberZulu** [comment]
Hell, are there any updates about the release date? It is April already... Thank you!

**Comment by rodnymolina** [comment]
@NovemberZulu, thanks for your patience. We finally published the latest v0.6.1 release which includes support for Kubernetes v1.24 to v1.26.

Closing this issue now.

**Comment by mike-chen-samsung** [comment]
Just an FYI that the Enterprise Edition K8s manifests still point to the old image, `registry.nestybox.com/nestybox/sysbox-ee-deploy-k8s:v0.5.2`: https://raw.githubusercontent.com/nestybox/sysbox/master/sysbox-k8s-manifests/sysbox-ee-install.yaml

**Comment by ctalledo** [comment]
Hi @mike-chen-samsung, yes this is on purpose: Sysbox-EE will no longer be sold, so we are not updating it.  Thanks for the notice.

**Comment by DekusDenial** [comment]
Does 16 pod/node restriction still apply in sysbox ce?

**Comment by ctalledo** [comment]
Hi @DekusDenial: no, the 16 pods per limit restriction has been lifted in Sysbox CE v0.6.1. Hope that helps!

**Comment by Tijmen34** [comment]
@ctalledo should the docs be updated to reflect that change? [Following docs](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/limitations.md#kubernetes-restrictions) still state that the limitation is there.

**Comment by ctalledo** [comment]
Hi @Tijmen34 , docs have been updated now. Thanks.
