### ISSUE TITLE
Request timeout while trying to configure Sysbox on a Kubernetes Node

### ISSUE THREAD

**Issue by Deepansharora27** [nestybox/sysbox#631]
Hi, 

When I am trying to configure/install SysBox on a Kubernetes Cluster through the `sysbox-deploy-k8s` daemonset via 

`kubectl apply -f https://raw.githubusercontent.com/nestybox/sysbox/master/sysbox-k8s-manifests/sysbox-install.yaml`

The Request times out and I get a Response timeout error:
`Unable to connect to the server: dial tcp [2405:200:1607:2820:41::36]:443: i/o timeout`

Does the Issue persist at the API level when I am trying to ping the API or is it something else ?

**Comment by rodnymolina** [comment]
Hi @Deepansharora27, at first glance it looks like a connectivity issue with our image registry.

Are you able to manually fetch the docker image we are pointing to within the `sysbox-install.yaml`? For example, does this works for you?

`docker pull registry.nestybox.com/nestybox/sysbox-deploy-k8s:v0.5.2`

**Comment by Deepansharora27** [comment]
@rodnymolina I am able to fetch this manually, but while doing using it with `kubectl apply -f`, the request times out

**Comment by Deepansharora27** [comment]
Also, another question that I have is that Suppose I have a up and running SysBox Container and I want to deploy it to a Kubernetes Cluster. In order for me to deploy it to a Kubernetes Cluster, will I need to first configure SysBox on the Cluster and then deploy my SysBox Container or can I directly deploy my SysBox Container without configuring SysBox on the Kubernetes Cluster ? @rodnymolina @ctalledo

**Comment by rodnymolina** [comment]
@Deepansharora27, I'm not sure why `kubectl apply` fails for you, but could you adjust our install/uninstall [manifests](https://github.com/nestybox/sysbox/tree/master/sysbox-k8s-manifests) to point to this image: `hcr.io/nestybox/sysbox-deploy-k8s:v0.5.2`. By doing this you are bypassing our proxy which might serve as a workaround for you (assuming there's some funky firewalling issue affecting you).

To answer your second question, yes, you would need to install Sysbox in your cluster before you are able to instantiate a container powered by Sysbox.

**Comment by rodnymolina** [comment]
We are seemingly dealing with a networking/firewalling issue and not a Sysbox-specific problem. Closing issue for now. Please re-open if the problem persists.
