### ISSUE TITLE
cannot start docker inside docker with --runtime=sysbox-runc

### ISSUE THREAD

**Issue by raquelhortab** [nestybox/sysbox#635]
Hi, I came across this project while looking for safe solutions for running containers inside containers.  (I read about it [here](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/))

However, if I run a docker container on the host:

```
docker run -it --runtime=sysbox-runc ubuntu:18.04
```

install docker, start docker service and check it's running...

```
$ curl -fsSL https://get.docker.com | sh
$ service docker start 
 * Starting Docker: docker                                                                                                                  [ OK ] 
$ service docker status
 * Docker is running
```
everything seems fine, but if I try running another container inside this one:

```
docker run -d --name cont1 ubuntu:18.04
```

it fails

```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: mkdir /sys/fs/cgroup/rdma/docker/26aba699070e99feb913640489664d9e4d4be48141edfdeafe24081bb8324567: permission denied: unknown.
```

My host its a laptop running ubuntu 20.04 and I installed sysbox following the instructions [here](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-package.md#installing-sysbox).

This was me just trying if/how sysbox works but my intention is to use it to run a container in a server, this container should ba able to run some containers inside  without having access to the outer containers (so without any special privileges whatsoever)

Thanks in advance!

**Comment by ctalledo** [comment]
BTW,

> This was me just trying if/how sysbox works but my intention is to use it to run a container in a server, this container should ba able to run some containers inside without having access to the outer containers (so without any special privileges whatsoever)

That's a perfect use case for Sysbox, as it will allow you to run Docker-in-Docker in a very easy way and without using privileged containers.

**Comment by raquelhortab** [comment]
Oh amazing, it works now, thanks!! Maybe it'd be nice to modify the install instructions so it installs the latest version

**Comment by raquelhortab** [comment]
@ctalledo  is sysbox compatible with this OS? how could I correctly install the latest version there?

```
Operating System: Rocky Linux 8.6 (Green Obsidian)
CPE OS Name: cpe:/o:rocky:rocky:8:GA
Kernel: Linux 4.18.0-372.32.1.el8_6.x86_64
Architecture: x86-64
```

this is the partial output of `hostnamectl`

**Comment by raquelhortab** [comment]
oh, judging by this I guess it's not compatible 

![image](https://user-images.githubusercontent.com/19463905/216272046-46cfb429-1734-4e7f-b9e4-ac019f2c205a.png)

too bad we won't be able to use it then

**Comment by ctalledo** [comment]
Hi @raquelhortab, glad you got it to work, but yes, both the kernels you mentioned above are a bit too old as Sysbox works best with kernel 5.5+ (and preferably 5.12+).

Closing this issue, please re-open if you need any further help. Thanks!
