### ISSUE TITLE
Error : value too large for defined data type caused

### ISSUE THREAD

**Issue by Vaunorage** [nestybox/sysbox#654]
I followed the tutorial for installing sysbox, but when I got to this line : 

`docker run --runtime=sysbox-runc -P -d nestybox/ubuntu-bionic-systemd-docker
`
I got his error : 

`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: container_linux.go:425: starting container process caused: process_linux.go:607: container init caused: process_linux.go:578: handleReqOp caused: rootfs_init_linux.go:366: failed to mkdirall /var/lib/sysbox/shiftfs/bec40c1d-957b-43af-99ee-67680a8689ed/var/lib/rancher/rke2: mkdir /var/lib/sysbox/shiftfs/bec40c1d-957b-43af-99ee-67680a8689ed/var/lib/rancher: value too large for defined data type caused: mkdir /var/lib/sysbox/shiftfs/bec40c1d-957b-43af-99ee-67680a8689ed/var/lib/rancher: value too large for defined data type: unknown.`

I am running Mint version 21.1 and Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2.

My linux kernel is : 5.15.0-67-generic
My shiftfs : 5.15.0-67-generic SMP mod_unload modversions

Do you have any idea why this is happening ?

**Comment by Vaunorage** [comment]
There seems to be a problem with kernel 5.15 for shiftfs as described here : 

https://stackoverflow.com/questions/75343570/sysbox-runc-is-not-working-as-runtime-for-docker-in-ubuntu

Trying to upgrade to newer verison of shiftfs

**Comment by Vaunorage** [comment]
Solution : disable shifts thanks to https://github.com/nestybox/sysbox/issues/596#issuecomment-1297185361
`sudo mkdir -p /etc/systemd/system/sysbox-mgr.service.d && printf '%s\n' '[Service]' 'ExecStart=' 'ExecStart=/usr/bin/sysbox-mgr --disable-shiftfs' | sudo tee /etc/systemd/system/sysbox-mgr.service.d/override.conf && sudo systemctl daemon-reload && sudo systemctl restart sysbox`

**Comment by ctalledo** [comment]
Hi @Vaunorage, thanks for trying Sysbox and sorry you hit this issue with shiftfs, but glad you were able to find the work-around.
