### ISSUE TITLE
Sysbox 0.6.1 the K8S installer for 1.22 is missing crio-patched binary

### ISSUE THREAD

**Issue by vandycknick** [nestybox/sysbox#676]
While installing the latest sysbox version (0.6.1) on a clean K8S cluster running v1.22. I ran into the following issue:

```sh
Detected Kubernetes version v1.22
Adding K8s taint "sysbox-runtime=not-running:NoSchedule" to node ...
node/192-168-56-11--node modified
Adding K8s label "crio-runtime=installing" to node ...
node/192-168-56-11--node not labeled
Deploying CRI-O installer agent on the host (v1.22) ...
cp: cannot stat '/opt/crio-deploy/bin/v1.22/crio-patched': No such file or directory
```

The patched crio binary for v1.22 is missing:

![Screenshot 2023-04-17 at 14 50 03](https://user-images.githubusercontent.com/6469315/232489912-043257ed-3b61-4380-8bf1-e14d1d984cf7.png)

**Comment by ctalledo** [comment]
Hi @vandycknick, installation of Sysbox on K8s v1.22 is no longer supported (v1.22 is EOL'd).

**Comment by vandycknick** [comment]
Thanks for the update. That wasn't immediately obvious to me. The installer script already has a check to see if the k8s version is compatible. It might be nice to add the v1.22 version to the not supported list here aswell 😄

```sh
function is_supported_k8s_version() {

        local ver=$k8s_version

        if [[ "$ver" == "v1.22" ]] ||
                [[ "$ver" == "v1.23" ]] ||
                [[ "$ver" == "v1.24" ]] ||
                [[ "$ver" == "v1.25" ]] ||
                [[ "$ver" == "v1.26" ]]; then
                return
        fi

        if [[ "$ver" == "v1.19" ]] ||
                [[ "$ver" == "v1.20" ]] ||
                [[ "$ver" == "v1.21" ]]; then
                echo "Unsupported kubernetes version: $ver (EOL release)."
        fi

        false
}
```

**Comment by ctalledo** [comment]
Oh thanks for catching that, I'll fix it.

> I would make a PR but have no idea where this script is managed.

We will be open-sourcing that code very soon (in the coming days).
