### ISSUE TITLE
Ubuntu Focal displays 'setrlimit' error during 'sudo' execution

### ISSUE THREAD

**Issue by rodnymolina** [nestybox/sysbox#68]
The following error is dumped to console whenever a command is executed through 'sudo' interface:

```
admin@test-3:~$ touch test

admin@test-3:~$ ls
test

admin@test-3:~$ sudo ls
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
test

admin@test-3:~$
```

Notice that the instruction is properly executed so it looks like a cosmetic issue. In either case, problem has nothing to do with Sysbox, and in fact it's being actively worked on by Canonical folks:

https://bugs.launchpad.net/juju/+bug/1867799
https://discuss.linuxcontainers.org/t/sudo-on-ubuntu-20-04-focal/7508/4

I'm creating this issue to make sure we update our external Docker images (and associated Dockerfiles) once that problem is fixed, which may require updating the 'sudo' package.

**Comment by rodnymolina** [comment]
We are dealing with a 'sudo' issue here, so there's not much to do from our side other than waiting for a fix to update our sample Docker images.

**Comment by ctalledo** [comment]
Closing as there are no actions here for Sysbox.
