### ISSUE TITLE
Master branch doesn't contain release tags past v0.2.0

### ISSUE THREAD

**Issue by arcivanov** [nestybox/sysbox#683]
It seems that the tags do not appear in the master branch past certain release version.
Is it possible to merge the release commits into master to make the branches consistent?

```
bash-5.2$ git tag -l
v0.1.0
v0.1.1
v0.1.2
v0.2.0
v0.2.1
v0.3.0
v0.4.0
v0.4.1
v0.5.0
v0.5.1
v0.5.2
v0.6.1
bash-5.2$ git log --pretty='%H%d' --decorate-refs=refs/tags --decorate=short HEAD | grep tag
5c0f70dd2a0ce25ef5af0e7634498b9d01cb4de4 (tag: v0.2.0)
331ac687f6ce7c2868fcad57ede94d385b3f048d (tag: v0.1.2)
04b138db74d96b14e99e44ed1b23cc4ed75ec03a (tag: v0.1.1)
1c76731e97b488402526119d4bbd5ea8fdca339a (tag: v0.1.0)
```

**Comment by rodnymolina** [comment]
Hi @arcivanov, not sure I follow, the tags are present in the master branch as we can see from your `git tag -l` output above.

Doesn't this provide the information you're after: `git show v0.6.1`?

Please let me know if I didn't get your point.

**Comment by arcivanov** [comment]
`git tag -l` doesn't list tags in a branch, it lists all tags available everywhere.
This is the command to demonstrate that the tags are present.

The second command `git log` demonstrates that the tagged commits do not appear in the master branch since tag `v0.2.0`. To verify, simply create a PR of `release_v0.6.1` into `master` and observe that the tagged commit isn't there.

**Comment by arcivanov** [comment]
```
bash-5.2$ git checkout release_v0.6.1
M       sysbox-libs
Switched to branch 'release_v0.6.1'
Your branch is up to date with 'origin/release_v0.6.1'.
bash-5.2$ git log -1
commit d3bdc694ef6a540f4c4f26dd3735a1882a516b92 (HEAD -> release_v0.6.1, origin/release_v0.6.1)
Author: Rodny Molina <rodny.molina@docker.com>
Date:   Fri Apr 7 21:34:53 2023 +0000

    Release v0.6.1
    
    Signed-off-by: Rodny Molina <rodny.molina@docker.com>
bash-5.2$ git checkout master
M       sysbox-fs
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
bash-5.2$ git checkout master
M       sysbox-fs
Already on 'master'
Your branch is up to date with 'origin/master'.
bash-5.2$ git log | grep d3bdc694ef6a540f4c4f26dd3735a1882a516b92
bash-5.2$
```

**Comment by arcivanov** [comment]
I worked around it by tracking the last commit into the VERSION file, but this is still a problem.

**Comment by ctalledo** [comment]
Hi @arcivanov, this is the way U usually checkout the source for a given release tag:

```
$ git fetch --all --tags
$ git checkout tags/v0.6.1-0 -b v0.6.1-0
$ cd sysbox-mgr && git checkout master && cd ..
$ cd sysbox-fs && git checkout master && cd ..
$ cd sysbox-runc && git checkout master && cd ..
$ cd sysbox-ipc && git checkout master && cd ..
```

Hope that helps.

**Comment by arcivanov** [comment]
Yeah, my goal was to count the number of commits since the last tag. :smile: 
I worked around that by finding the last change to the VERSION file and counting to HEAD from there. 

Thanks!
