### ISSUE TITLE
Sysbox daemonset installer fails to detect RKE2 in single-node cluster 

### ISSUE THREAD

**Issue by detjensrobert** [nestybox/sysbox#692]
On a single-node RKE2 cluster, the kubelet config helper service/script does not correctly detect that RKE2 is running as a single-node cluster and attempts to use the systemd-based configuration which fails as in #614.

The first node in the RKE2 cluster runs as `rke2-server.service`, and not `rke2-agent.service` that the install script is expecting to see. This causes A) the script to not detect RKE2 in `kubelet_rke2_deployment()`, and if the check is patched to also look for `rke2-server` B) not stop/restart the correct service.

## Reproduction

- On a clean VM e.g. Ubuntu 22.04, install latest RKE2 via the quick install script per https://docs.rke2.io/install/quickstart
- Start the server node `systemctl enable --now rke2-server.service`
- Install the sysbox install daemonset into the new cluster per https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md
- observe `kubelet-config-helper.service` trying to configure via 'systemd-managed host-based kubelet deployment' instead of via RKE2

Is the repo for the daemonset installer open source? I would be happy to propose a PR.

**Comment by rodnymolina** [comment]
@detjensrobert, thanks for your detailed analysis.

You are right, the `sysbox-k8s-deploy` daemonset expects to be deployed in nodes acting as k8s-nodes, and not as k8s-controllers. We would need to think about how to fix this limitation for single-node clusters. And yes, we would be happy to review your PR -- we will be open-sourcing this code very shortly, will ping you when done. Thanks.

**Comment by rodnymolina** [comment]
@detjensrobert, we just went ahead and made our [sysbox-pkgr](https://github.com/nestybox/sysbox-pkgr/tree/68f3e81a4f50b1b37e96ad665451bee57ee545a5) repo public. You can either git-clone it individually or you can clone indirectly through our top-most [sysbox](https://github.com/nestybox/sysbox-pkgr/tree/68f3e81a4f50b1b37e96ad665451bee57ee545a5) repository (i.e., `sysbox-pkgr` is now a git-submodule of `sysbox`).

I'm planning to write some documentation to explain the structure of this repo, but in the meantime you can already make the changes that you were thinking about in [this](https://github.com/nestybox/sysbox-pkgr/blob/68f3e81a4f50b1b37e96ad665451bee57ee545a5/k8s/scripts/kubelet-config-helper.sh) file. Let us know if any questions.
