### ISSUE TITLE
Kubernetes 1.27 support

### ISSUE THREAD

**Issue by stijndehaes** [nestybox/sysbox#704]
According to [documentation](https://github.com/nestybox/sysbox/blob/6120a03f7eeb0d05aef7b4931e5ad155de633011/docs/user-guide/install-k8s.md#kubernetes-version-requirements) version 1.24 until 1.26 of kubernetes is supported. Is there any work that needs to be done to support 1.27?

**Comment by ctalledo** [comment]
Hi @stijndehaes, yes there is some work required:

1) Update CRI-O to v1.27.
2) Update sysbox-deploy-k8s K8s version checking to allow v1.27.
3) Test that sysbox-deploy-k8s works on K8s v1.27 across the major cloud distros (GKE, EKS, AKS, etc.)

This is typically 2->3 days of work best case, particularly step (3).

Given that v1.27 was just released a few days ago, I don't think we will get to it for a few weeks at least.

**Comment by stijndehaes** [comment]
Just so you know 1.27 is GA on AWS, Azure and Google :)

**Comment by ctalledo** [comment]
Hi @stijndehaes, apologies for the delay, sysbox-deploy-k8s now supports K8s v1.27.

Closing.

**Comment by stijndehaes** [comment]
@ctalledo thank you for releasing this!
