### ISSUE TITLE
Add a comparison section in the documentation

### ISSUE THREAD

**Issue by felipecrs** [nestybox/sysbox#71]
It would be very nice if we could have a comparison section in the documentation, just like [kubespray have](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/comparisons.md).

To start with, I think we could compare it to [Kata Containers](https://github.com/kata-containers/kata-containers).

**Comment by ctalledo** [comment]
Thanks for the suggestion @felipecrs, makes sense, we will work on this soon.

**Comment by ctalledo** [comment]
Hi @felipecrs, thanks again for filing this issue.

We've created an article on the Nestybox blog site that compares Sysbox with many alternative technologies:

https://blog.nestybox.com/2020/10/06/related-tech-comparison.html

I've added a link to it from the Sysbox README file too.

Hope this helps!

Closing the issue.

**Comment by felipecrs** [comment]
Amazing article, @ctalledo. I really enjoyed reading it. Thanks!

**Comment by ctalledo** [comment]
Anytime @felipecrs !
