### ISSUE TITLE
Sysbox build attributes missing from "--version" output

### ISSUE THREAD

**Issue by myugan** [nestybox/sysbox#73]
I following the guide from here https://github.com/nestybox/sysbox/blob/master/docs/developers-guide/build.md, download the source code from the release page but it's failed when try to run `make sysbox` like this:

**OS version**: `Ubuntu 18.04.5 LTS`
**Kernel version**: `5.4.0-48-generic #52~18.04.1-Ubuntu SMP`

```
** Building sysbox **

docker run --privileged --rm --hostname sysbox-build --name sysbox-build -v /root/sysbox-0.2.1:/root/nestybox/sysbox -v /root/go/pkg/mod:/go/pkg/mod -v /lib/modules/5.4.0-48-generic:/lib/modules/5.4.0-48-generic:ro -v /usr/src/:/usr/src/:ro -v /usr/src/:/usr/src/:ro sysbox-test /bin/bash -c "buildContainerInit sysbox-local"
cd sysbox-runc && make clean
make[1]: Entering directory '/root/nestybox/sysbox/sysbox-runc'
make[1]: Leaving directory '/root/nestybox/sysbox/sysbox-runc'
make[1]: *** No rule to make target 'clean'.  Stop.
Makefile:325: recipe for target 'clean' failed
make: *** [clean] Error 2
Makefile:110: recipe for target 'sysbox' failed
make: *** [sysbox] Error 2
```

**Comment by rodnymolina** [comment]
@myugan, are you sure that you git-clone Sysbox making use of the "--recursive" flag as indicated in our doc? (we have a various repos within Sysbox project).

```
git clone --recursive git@github.com:nestybox/sysbox.git
```

Let me know if any problem.

**Comment by myugan** [comment]
Okay, I guess the source code will contain all of the code instead of `--recursive` flag using git command, and now it's working but when I try `sysbox-runc -v` there is and output only at `oci-specs` like this:

```
sysbox-runc
        version:
        commit:
        built at:
        built by:
        oci-specs:      1.0.2
```

is that ok?

**Comment by rodnymolina** [comment]
Thanks @myugan, you have encountered a bug in our build-infrastructure logic, which is preventing these attributes (version/commit/build-at, etc) from being properly passed to the sysbox builder container. This was probably introduced a few weeks ago when we made some Makefile changes.

However, please keep in mind that none of this will impact Sysbox functionality, as we are dealing with a cosmetic issue here.

Btw, I'll go ahead and adjust this issue's title to reflect the problem that you just found. Please change it if you find a better title.

**Comment by ctalledo** [comment]
Hi @myugan,

> However, please keep in mind that none of this will impact Sysbox functionality, as we are dealing with a cosmetic issue here.

Do you agree with @rodnymolina comment here? Or is this more than a cosmetic issue for you?

**Comment by myugan** [comment]
I'm agreed @ctalledo

**Comment by ctalledo** [comment]
Thanks @myugan ; let's leave the issue open and we will get to it soon (we definitely want to fix it). In the meantime let us know of any other issue you hit, we appreciate you trying Sysbox.

**Comment by ctalledo** [comment]
This was fixed back in 01/2021 and will be present in the upcoming 0.3.0 release.

```
root@sysbox-test:~/nestybox/sysbox# sysbox-runc --version
sysbox-runc
        version:        0.3.0-dev
        commit:         "0e845604d5f62365825df03b305f18eb706ccbb5"
        built at: 
        built by: 
        oci-specs:      1.0.2-dev
root@sysbox-test:~/nestybox/sysbox# sysbox-fs --version
sysbox-fs
        version:        0.3.0-dev
        commit:         "4fe6862a6d2114827f4977959b683101bf90a252"
        built at: 
        built by: 
root@sysbox-test:~/nestybox/sysbox# sysbox-mgr --version
sysbox-mgr
        version:        0.3.0-dev
        commit:         "95010ecb3e813d75ec8b523bd8f6d8890dfa26e6"
        built at: 
        built by: 
```

**Comment by ctalledo** [comment]
Closing.
