### ISSUE TITLE
Higher memory usage if more vCPU is available

### ISSUE THREAD

**Issue by gmandity** [nestybox/sysbox#733]
Hi,
We are using currently the latest (v0.6.2) Sysbox version in our environment. Lately we had a blocker upgrading from v0.4.1, because containers started hanging after we upgraded to a later version.
It took us some time to realize, that the memory usage of the containers is simply higher if we are using Sysboc v0.5.0, v0.5.2 or v0.6.2 if more vCPU is available on the node.
We have test VMs with 4 vCPU and 16 GB memory, while in production environment we are using VMs with 8 vCPU and 64 GB memory. The same container with the same workload (we were building the same Java application inside the Docker container) used less memory in the test environment. As soon as we increased the vCPU count to 8 in the test environment as well, we were facing the same issue: the container started to use more memory.

Luckily it's not a blocking issue, as we have plenty of memory available, so we could raise the memory limit for the containers. But I am curious, if it's the intended behaviour?

Thank you for the answer.

**Comment by ctalledo** [comment]
Hi @gmandity, thanks for using Sysbox.

Just so I understand, is the question (1) why the container uses more memory when the host CPU/RAM increases, or is the question (2) is there a difference in container mem utilization between Sysbox v0.4.1 and v0.6.2?

For the first question, I think that unless you are constraining the container's CPU/mem utilization with cgroups, the container will use as much as needed within the limits of what the host makes available. 

For the second question, I am not aware of any differences between Sysbox v0.4.1 and v0.6.2 that could cause this, and generally Sysbox stays away from container CPU & mem utilization (it only sets up the cgroup limits for the container as dictated by the higher level runtime (e.g., Docker or K8s)).

**Comment by gmandity** [comment]
Hi @ctalledo,
Thank you for your answer! My question was more like a mix of the two, if anything could cause higher memory usage if more CPU is available for the container.
I will read the Docker documentation about this topic, how it could be fine tuned, but for now having higher memory limits is OK for us.
