### ISSUE TITLE
K8s FailedCreatePodSandBox: Failed to create pod sandbox not enough unused IDs in user namespace 

### ISSUE THREAD

**Issue by AlperRehaYAZGAN** [nestybox/sysbox#737]
Hello everyone.  
  
I just started using sysbox to handle our ci-cd processes. I followed the documentation and installed k8s ubuntu 22.04 (one master one worker), In worker node I installed both [deb package](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-package.md#installing-sysbox) and [k8sMaster provided apply command](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#installation-of-sysbox). After that I installed shiftfs module for new [version 6.1 support](https://github.com/toby63/shiftfs-dkms/tree/k6.1). But [After applying test pod from master via kubectl](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#pod-deployment). I see error below. I think thats relevant with sysbox user mapping flow. How can i solve that?
  
Error is: 
```bash
2m12s (x25 over 7m14s)   Warning   FailedCreatePodSandBox    Pod/ubu-focal-systemd-docker   Failed to create pod sandbox: rpc error: code = Unknown desc = creating pod sandb
ox with name "k8s_ubu-focal-systemd-docker_default_6396155d-a9f7-45c1-adea-ce7dcfed7f49_0": not enough unused IDs in user namespace
```   
### Master machine logs (sysbox installed via k8s apply command and tried to deploy test pod from documentation)
![image](https://github.com/nestybox/sysbox/assets/43668181/6a7b3825-0a1a-4931-bc57-8d88b3c30da8).  
  
### Worker Node. (crio.conf file updated manually and restarted)   
sysbox installed additional via .deb package into machine independent from k8s apply command
![image](https://github.com/nestybox/sysbox/assets/43668181/a524599c-3a9a-4e5f-8fd7-995fcab30ccc)

**Comment by AlperRehaYAZGAN** [comment]
I found something like this but I dont have any idea that unused IDs means that crio's problem.

https://frasertweedale.github.io/blog-redhat/posts/2020-12-01-openshift-crio-userns.html

**Comment by rodnymolina** [comment]
@AlperRehaYAZGAN, thanks for filling this one up.

Please keep in mind that you do not need to install Sysbox through its deb package manually. In Kubernetes scenarios, you need to follow [this](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#installation-of-sysbox) procedure to have sysbox installed and properly configured. Please wipe out this scenario and start from scratch by following this procedure. Let us know if you run into any issues.

**Comment by ctalledo** [comment]
Hi @AlperRehaYAZGAN, per Rodny's prior comment, it seems we can close this ticket; can you confirm please? Thanks!

**Comment by AlperRehaYAZGAN** [comment]
Hey folks, I SOLVED THE ISSUE!

**The Real Problem is:**
First of all, thank you for the updates (@rodnymolina , @ctalledo , @haseoleonard ). The situation I encountered was as follows. I set up a K8S v1.26 cluster on an Ubuntu 22.04 machine with one master and three worker nodes, following the installation [EXAMPLE](https://akyriako.medium.com/install-kubernetes-on-ubuntu-20-04-f1791e8cf799).  
  
After the Kubernetes installation, I followed the installation on three worker machines one by one with the `kubectl apply ...sysbox-install.sh` command, as shown in the [SysBox_K8S_Installation_Guide](https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-k8s.md#installation-of-sysbox). Sysbox was installed on all three machines without any problems. There was no issue during the installation. After the installation, when I went to those three machines, I checked that Sysbox automatically installed the CRI-O tool, and it did.  
  
The problem I encountered was that whenever I tried to create a container, the container creation request was received by the Kubernetes master node, but the worker node gave an error for "runtimeClassName: sysbox-runc". After extensive research, I found the following problem:

**Problem 1:**.  
- When Sysbox installs the default CRI-O during Kubernetes installation, it does not create the necessary [Linux user named "containers"](https://github.com/cri-o/cri-o/blob/main/tutorials/userns.md). Therefore, I could not see the "containers" user in the output of the `cat /etc/subuid` command in myfirst comment photo (above).

**Solution 1:**
- To create "containers" user, the `adduser containers` command must be run on **each worker machine**. After creating the user, check username in **"/etc/subuid"** file entry like `containers:165536:65536`

**Problem 2:**.  
- Due to the `io.kubernetes.cri-o.userns-mode: "auto:size=65536"` annotation, the 65536 namespace quota allocated for the "containers" user is depleted when only one container is created. Even if the first pod is created successfully, you will encounter the same error when creating the second pod. Because all 65536 namespace allocated from first pod. So you should update namespace spaces manually.

**Solution 2:**.  
- For the user you created with `adduser containers`, manually update the value "65536" to "16777216" (which is "65536 * 256 = 16777216") in the "/etc/subuid" and "/etc/subgid" files. After updating, restart the system by saying "reboot now" to assign that namespace range to the user.

Final **"/etc/subuid"** and **"/etc/subgid"** files should looks like this:

```
ubuntu:100000:65536
sysbox:165536:65536
containers:231072:16777216
```

**Comment by ctalledo** [comment]
Hi @AlperRehaYAZGAN,

Thanks for the update, glad you got it working.

> It seems that Sysbox K8S default installation process does not creates and updates namespaces for user containers instead of sysbox

That's strange; the sysbox-k8s-deploy daemonset should be doing that, see [here](https://github.com/nestybox/sysbox-pkgr/blob/6b3ab3cb0ad847e6e3a820baddc774f95207c415/k8s/scripts/sysbox-deploy-k8s.sh#L212).  Without this no users would be able to use K8s + Sysbox properly, so I am confident it works.

Having said that, something must have failed in your setup though, but not sure why.
