### ISSUE TITLE
Please add support for Kubernetes 1.28

### ISSUE THREAD

**Issue by jstewart612** [nestybox/sysbox#755]
```
ERROR: Sysbox is not supported on this Kubernetes version (v1.28).
```

**Comment by mattlqx** [comment]
Any updated ETA?

**Comment by ctalledo** [comment]
Hi @mattlqx,

> Any updated ETA?

Should be ready before this weekend, unless I hit any unforeseen issues. Thanks!

**Comment by stijndehaes** [comment]
@ctalledo thank you for the new release 🎉

**Comment by ctalledo** [comment]
Closing as Sysbox v0.6.3 supports K8s 1.28.
