### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by anveshmuppeda** [nestybox/sysbox#784]
Hi,

When I am trying to run **ubuntu-bionic-docker** with runtime=sysbox-run, docker service isn't starting inside my docker container automatically. 
So here I am running it manually by logging inside container.   
**But is there any way that we can start docker service automatically when running the container?**   

### sysbox status
```
sudo systemctl status sysbox -n20
● sysbox.service - Sysbox container runtime
     Loaded: loaded (/lib/systemd/system/sysbox.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2024-03-02 08:44:02 UTC; 18s ago
       Docs: https://github.com/nestybox/sysbox
   Main PID: 4457 (sh)
      Tasks: 2 (limit: 4575)
     Memory: 428.0K
        CPU: 32ms
     CGroup: /system.slice/sysbox.service
             ├─4457 /bin/sh -c "/usr/bin/sysbox-runc --version && /usr/bin/sysbox-mgr --version && /usr/bin/sysbox-fs --version &>
             └─4475 /bin/sleep infinity
```  

### Command used to run my container    
```
docker run --runtime=sysbox-runc -it nestybox/ubuntu-bionic-docker:latest
```  

### Docker status inside my container.   

```
root@43a09fbb2ade:/# docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@43a09fbb2ade:/# 
root@43a09fbb2ade:/# 
root@43a09fbb2ade:/# service docker status
 * Docker is not running
root@43a09fbb2ade:/# 
root@43a09fbb2ade:/# service docker start 
mount: /sys/fs/cgroup/cpuset: permission denied.
mount: /sys/fs/cgroup/cpu: permission denied.
mount: /sys/fs/cgroup/cpuacct: permission denied.
mount: /sys/fs/cgroup/blkio: permission denied.
mount: /sys/fs/cgroup/memory: permission denied.
mount: /sys/fs/cgroup/devices: permission denied.
mount: /sys/fs/cgroup/freezer: permission denied.
mount: /sys/fs/cgroup/net_cls: permission denied.
mount: /sys/fs/cgroup/perf_event: permission denied.
mount: /sys/fs/cgroup/net_prio: permission denied.
mount: /sys/fs/cgroup/hugetlb: permission denied.
mount: /sys/fs/cgroup/pids: permission denied.
mount: /sys/fs/cgroup/rdma: permission denied.
mount: /sys/fs/cgroup/misc: permission denied.
 * Starting Docker: docker                                                                                                 [ OK ] 
root@43a09fbb2ade:/# 
root@43a09fbb2ade:/# service docker status
 * Docker is running
root@43a09fbb2ade:/# 
```

Can someone please help me here?

**Comment by ctalledo** [comment]
Hi @anveshmuppeda, thanks for giving Sysbox a shot, hope you find it helpful.

The `ubuntu-bionic-docker` image includes Docker Engine in it, but does not start it automatically; if you wish to use this image, you have to start Docker Engine inside the container manually:

```
$ docker run --runtime=sysbox-runc -it --rm nestybox/ubuntu-bionic-docker

root@bf5a22b6bafe:/# docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

root@bf5a22b6bafe:/# dockerd > /var/log/dockerd.log 2>&1 &
[1] 83
root@bf5a22b6bafe:/# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

If you want Docker Engine to start automatically, the easiest way is to use the `nestybox/ubuntu-bionic-systemd-docker` image, which includes systemd as the process manager inside the container and it starts docker engine automatically.

```
$ docker run --runtime=sysbox-runc -it --rm nestybox/ubuntu-bionic-systemd-docker
...
7ce735b157d6 login: admin
password: admin
...
admin@7ce735b157d6:~$ docker ps
```

If systemd is too heavy, you can use a lighter weight process manager such as `supervisord` (see [this example Dockerfile](https://github.com/nestybox/dockerfiles/tree/master/alpine-supervisord-docker)).

Note that the above Docker images are provided for reference only. The Dockerfiles are [here](https://github.com/nestybox/dockerfiles/tree/master) and you can copy them and modify them to your needs. 

Hope that helps!

**Comment by ctalledo** [comment]
(Closing issue, please re-open if neccesary).

**Comment by anveshmuppeda** [comment]
@ctalledo 
I appreciate your swift response; it made a significant difference for me.
