### ISSUE TITLE
Error in supervisord.conf of jenkins exemplary docker file

### ISSUE THREAD

**Issue by sebastian-peter** [nestybox/sysbox#786]
While using the exemplary Dockerfile for Jenkins, I came across something that looks like an error in [supervisord.conf](https://github.com/nestybox/dockerfiles/blob/5b7ec2230af7fb65eb820277e8c408cfa68f79b7/jenkins-syscont/supervisord.conf#L18C1-L18C17). 

The jenkins process is configured with `username=jenkins`, but I think it should be `user=jenkins`. This could save the next person some time.

According to [supervisord.conf documentation](http://supervisord.org/configuration.html):

`username` belongs to configuration of `[unix_http_server]`, which is not what we're doing here.

`user` on the other hand:
    Instruct supervisord to use this UNIX user account as the account which runs the program. The user can only be switched if supervisord is run as the root user. If supervisord can’t switch to the specified user, the program will not be started.

**Comment by ctalledo** [comment]
Thanks @sebastian-peter for catching this. 

This means that supervisor.conf must have ignored `username` and therefore run Jenkins as root inside the Sysbox container (which is fine since it's root in the user-namespace of the container only, not on the underlying host machine). Nonetheless it's better to fix it to `user=jenkins`. I'll open a PR soon. Thanks!

**Comment by sebastian-peter** [comment]
I'm using a slightly different Dockerfile, so it's hard to be 100% certain. One more thing that is missing (once Jenkins is not ran by root anymore) is providing the `jenkins` user with the rights to use docker. Thus I added a line `usermod -aG docker jenkins` to the Dockerfile.

**Comment by ctalledo** [comment]
Fix PR: https://github.com/nestybox/dockerfiles/pull/40

**Comment by ctalledo** [comment]
PR merged, closing.
