### ISSUE TITLE
Docker Desktop Compatibility (Windows 11)

### ISSUE THREAD

**Issue by naderayed** [nestybox/sysbox#804]
Hello, 
I am trying to use Sysbox with Docker Desktop (WSL version: 2.0.14.0, Kernel version: 5.15.133.1-1). 
I am wondering if Sysbox supports my system or if I should use Ubuntu instead.

**Comment by ctalledo** [comment]
Hi @naderayed, thanks for your inquiry.

So there's a couple of options:

Docker Desktop includes Sysbox already, but uses it for a feature called [Enhanced Container Isolation](https://docs.docker.com/desktop/hardened-desktop/enhanced-container-isolation/). This is meant to secure development environments by running all containers in rootless mode. It also allows you to run Docker-in-Docker in rootless mode. Take a look at the link above and check if that's what you need.

Alternatively, if you want to use Sysbox with the basic Docker Engine (not Docker Desktop) on WSL, that also works. In that case you install Docker Engine and Sysbox on the Ubuntu WSL distro as you would on any other Ubuntu host.

Hope that helps.

**Comment by ctalledo** [comment]
Closing ...

**Comment by lsalazarm99** [comment]
@ctalledo Since "Enhanced Container Isolation" is a business feature, is there any other way to use Sysbox with Docker Desktop?

**Comment by ctalledo** [comment]
Hi @lsalazarm99, 

> Since "Enhanced Container Isolation" is a business feature, is there any other way to use Sysbox with Docker Desktop?

Not currently ... thanks.
