### ISSUE TITLE
Kubernetes 1.30 support

### ISSUE THREAD

**Issue by brentmitchell25** [nestybox/sysbox#814]
Please add kubernetes 1.30 support

**Comment by CyberHippo** [comment]
Hi @ctalledo, what would it take to add support for kubernetes 1.30?  I'm willing to help if needed

**Comment by ctalledo** [comment]
Sure @CyberHippo, thanks for the help, let's do it.

**Comment by aldcons** [comment]
Any idea when this might go in? Most of our clusters have been updated however the one we have using sysbox is falling behind.

**Comment by ctalledo** [comment]
With the help of @CyberHippo (thanks), we are making progress on this here: https://github.com/nestybox/sysbox-pkgr/pull/130

**Comment by yonirab** [comment]
Is there an ETA for sysbox support for k8s 1.30?

**Comment by stijndehaes** [comment]
This has been released: https://github.com/nestybox/sysbox/releases/tag/v0.6.5
So I believe this can be closed?

**Comment by ctalledo** [comment]
> So I believe this can be closed?

Yes, closing!
