### ISSUE TITLE
Fix installation instructions for RHEL-based distros

### ISSUE THREAD

**Issue by Reinitialized** [nestybox/sysbox#818]
# Overview
This issue is mostly for me since I've spent time diagnosing and getting the installation of sysbox onto AlmaLinux 9 working. Per the [contributing guidelines](https://github.com/nestybox/sysbox/blob/master/CONTRIBUTING.md#we-welcome-pull-requests), I will be creating a separate Pull Request containing these changes. It will be a bit as I just so happen to be reworking my development environment...

## Resolved Issues:
NOTE: This is a list of things I found and managed to resolve. I have yet to make the relevant changes in a Pull Request
- Self-compile documentation missing the following required dependencies: rsync, fuse
- Manually configuring systemd for self-compile documentation
- With the exception of `Dockerfile.rocky-9`, RHEL-based Dockerfiles will fail due to Google no longer hosting the required packages (now on pkgs.k8s.io)
- `dnf install -y  --enablerepo=devel libseccomp-static` fails due to missing devel repository. This might be caused by using a `Minimal Install` of a RHEL-based distro, not sure.
- Use the latest version of Kubernetes
- Drive of Docker volumes must use ext4 (not xfs as default within RHEL-based distros)

## Bonus Issues (if I can figure it out):
- Implement automated building of RPM for supported RHEL-based distros
  - NOTE: I believe a single package targeting versions 8/9 of all variants should be sufficient, but unsure. Wouldn't mind insight on this.

**Comment by Reinitialized** [comment]
A couple of questions geared toward the developers before I proceed with investing time into this:
- Is group/user ID mapping supported in any capacity with RHEL distros? I noted this functionality doesn't work (RHEL doesn't support shiftfs nor ID-mapped mounts afaict) when attempting to map `/var/run/docker.sock` for Portainer, but noted with the legacy Sysbox-EE support for RHEL was mentioned.
- If so, is there any known steps I can add to documentation to get this working? I ran into the `nobody:nogroup` issue and could not get around this with the exception of `chmod 0666 /var/run/docker.sock`, something I rather avoid for security concerns.

I'm aware with Sysbox, I can run Docker-in-Docker, but have my reasons for wanting a Sysbox Container to be capable of managing the Host docker. If RHEL is unable to support this in a secure manner at this time, then I currently see no reason to invest updating documentation around this at the moment until this is available.

**Comment by ctalledo** [comment]
Hi @Reinitialized, thanks for looking into this.

> Is group/user ID mapping supported in any capacity with RHEL distros? I noted this functionality doesn't work (RHEL doesn't support shiftfs nor ID-mapped mounts afaict) when attempting to map /var/run/docker.sock for Portainer, but noted with the legacy Sysbox-EE support for RHEL was mentioned.

ID-mapped mounts must definitely work, because it's part of the upstream Linux kernel since 5.12. No need to worry about shiftfs for now, ID-mapped-mappings replaces it.

> If so, is there any known steps I can add to documentation to get this working? I ran into the nobody:nogroup issue and could not get around this with the exception of chmod 0666 /var/run/docker.sock, something I rather avoid for security concerns.

So I can better help, what is the exact `docker run` command you are using?

> I'm aware with Sysbox, I can run Docker-in-Docker, but have my reasons for wanting a Sysbox Container to be capable of managing the Host docker. If RHEL is unable to support this in a secure manner at this time, then I currently see no reason to invest updating documentation around this at the moment until this is available.

Meaning you want to mount the host Docker's `/var/run/docker.sock` into the Sysbox container correct? That works perfectly fine and inside the Sysbox container you should see the `/var/run/docker.sock` with the appropriate ownership:

```
docker run --runtime=sysbox-runc -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker:cli

/ # ls -lL /var/run | grep docker.sock
srw-rw----    1 root     ping             0 Aug  2 00:33 docker.sock

/ # docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS          PORTS     NAMES
cae1486c8bb2   docker:cli                      "docker-entrypoint.s…"   15 seconds ago   Up 14 seconds             unruffled_booth
0237a79e3932   moby/buildkit:buildx-stable-1   "buildkitd --allow-i…"   2 months ago     Up 25 hours               buildx_buildkit_romantic_cannon0 
``` 

Should work in the exact same way on RHEL.

**Comment by Reinitialized** [comment]
Hello @ctalledo, thank you for your time!

I finally got around to testing this again, and it appears the issue was with RHEL-based distros defaulting to ext4. After setting up a test system using ext4, the docker.socket file is mounted with the correct permissions.

I will proceed with updating the information as originally planned.

**Comment by ctalledo** [comment]
Hi @Reinitialized, thanks for the latest update.

What's action-items (if any) are needed to close this issue?

Thanks!

**Comment by Reinitialized** [comment]
Hey there,

My apologies on this, I have been incredibly busy with my day job where I haven't had time to come back and address this. 

If you need to close the issue for now for statistics/reports, go ahead. I have it marked as unread on GitHub so I don't forget about this, and will address it once I have a moment to do so.

**Comment by ctalledo** [comment]
Thanks @Reinitialized, got it. 

Yes, let's close it and please re-open when you are ready. 

Thanks again!
