### ISSUE TITLE
how to switch runtime in swarm mode? Or connect Docker daemon at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by antonio24073** [nestybox/sysbox#819]
hi,
I have 2 containers with sysbox running containers inside.
So to do to work with `sysbox-runc` runtime, I changed my `daemon.json` like below:

```bash
$ cat /etc/docker/daemon.json 
{
    "default-runtime": "sysbox-runc",
    "runtimes": {
        "sysbox-runc": {
            "path": "/usr/bin/sysbox-runc"
        }
    },
    "userns-remap": "sysbox",
    "bip": "172.20.0.1/16",
    "default-address-pools": [
        {
            "base": "172.25.0.0/16",
            "size": 24
        }
    ]
}
```

But My other containers (portainer and traefik) that was running normally without sysbox-runc, is not working now. They run but with this warning:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Both have volumes like:

```yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

So, I'm not getting a way to put something like `runtime: runc` or `runtime: sysbox-runc` to change the `default-runtime` of the `daemon.json`. Or  maybe another method to connect the `docker.sock` of both. A specie of a bypass to sysbox to some containers or the other way around. 

All are in swarm mode.

best regards

**Comment by antonio24073** [comment]
In fact, I don't think there's a way to do that. I think if you change it to `sysbox-runc` it stays in all Docker anyway.

I got add the connection with a docker proxy from a normal container (not swarm) from project `tecnativa/docker-socket-proxy` using a bridge network and `privileged: true` and `userns_mode: host`

That's it. Solved. Thanks.

**Comment by ctalledo** [comment]
Hi @antonio24073,

> In fact, I don't think there's a way to do that.

Correct, I believe that Docker swarm lacks the ability to select the runtime per container (at least when using the Docker compose v3 schema; apparently earlier versions of the schema supported it). Thus you have to set `"default-runtime": "sysbox-runc",` in your Docker daemon.json file as you did.

> "userns-remap": "sysbox",

You should not need this when using Sysbox, because Sysbox will automatically enable the user-namespace in the containers. Nonetheless "userns-remap" works, but it's not required.

> But My other containers (portainer and traefik) that was running normally without sysbox-runc, is not working now. They run but with this warning:
>
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

That's strange; mounting a Docker socket into a Sysbox container works perfectly fine:

```
$ docker run --runtime=sysbox-runc -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker:cli

/ # docker version
Client:
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:55:52 2024
 OS/Arch:           linux/amd64
 Context:           default
```

**Comment by antonio24073** [comment]
You should not need this when using Sysbox, because Sysbox will automatically enable the user-namespace in the containers. Nonetheless "userns-remap" works, but it's not required.
> I don' t remember but here "userns-remap" was needed.


That's strange; mounting a Docker socket into a Sysbox container works perfectly fine

>  They are in docker swarm. I said that I had 2 containers with sysbox running containers inside. I did a simple container as you but with "runtime: runc" with a proxy of  "docker.sock" to get it with a bridged network inside the swarm node. But in the swarm only the runtime "sysbox-runc" works.

**Comment by antonio24073** [comment]
I removed "userns-remap". Apparently all right.

I'm using normal containers as `runc` or `sysbox-runc` and the swarm with the default `sysbox-runc`. 

But this feature (switch runtime in docker swarm) could be added in future versions.
