### ISSUE TITLE
Installing sysbox-ce package inside LXC container fails

### ISSUE THREAD

**Issue by maxulm** [nestybox/sysbox#860]
Hi,
I get the following error trying to install sysbox-ce (0.6.4.linux) on an lxc container with debian bookworm:
installed sysbox-ce package post-installation script subprocess returned error exit status 1
Could anyone help?

Regards
Max

**Comment by ctalledo** [comment]
Hi @maxulm, this is not something we've tried or support (i.e., installing sybox-ce inside an lxc container), but you can take a look at the Makefile in the Sysbox repo, where we have a [Make target](https://github.com/nestybox/sysbox/blob/186fca81273cbe401881e262b591e6a1bc09d124/Makefile#L368) that creates a Docker privileged container and install the Sysbox package in it.

Hope that helps.

**Comment by maxulm** [comment]
Hi @ctalledo ,
thanks for your reply.
Ubuntu 22.04 let me install it in lxc.

Regards
Max
