### ISSUE TITLE
Could not start POD on AKS Kubernetes Version 1.29.9

### ISSUE THREAD

**Issue by MrPeacockNLB** [nestybox/sysbox#864]
# Description

Just want to test the new release in out dev environment, but I could not start the POD. It says it can not run on v1.29

![image](https://github.com/user-attachments/assets/c8834d1f-662c-460f-9dd9-3d3d7d8944fd)

We run SysBox on Azure AKS cluster.

![image](https://github.com/user-attachments/assets/aafde979-e9bb-4c14-8c60-4b8e282a64b9)

Version v0.6.4 runs fine on the same cluster

**Comment by ctalledo** [comment]
Hi @MrPeacockNLB, thanks for reporting; yes there's [a mistake](https://github.com/nestybox/sysbox-pkgr/blob/eba1006690b26a525a26456bf0e991e6f26a44c7/k8s/scripts/sysbox-deploy-k8s.sh#L793) in the newest sysbox-deploy-k8s daemonset that prevents installation in v1.29.

We will fix it ASAP.

**Comment by rodnymolina** [comment]
@MrPeacockNLB, thanks for reporting this one. The issue has been fixed now. Please point the `sysbox-deploy-k8s` manifests to this new patched image: `registry.nestybox.com/nestybox/sysbox-deploy-k8s:v0.6.5-0.1`.

**Comment by rodnymolina** [comment]
Will close this one now. Please let us know if you run into any other issue.

**Comment by MrPeacockNLB** [comment]
I can confirm that SysBox starts now as expected
