### ISSUE TITLE
Are there plans to support k8s in WSL? Use kubeadm initialized cluster instead of k3s

### ISSUE THREAD

**Issue by yijiangchengming** [nestybox/sysbox#869]
It works fine in WSL, but it does not work if deployed as k8s in WSL.
Modified according to another issues，Error after custom kernel
`Error: path "/var/lib" is mounted on "/" but it is not a shared or slave mount
`

**Comment by ctalledo** [comment]
Hi @yijiangchengming, thanks for opening the issue.

No plans currently to support K8s + Sysbox on WSL as it's not a very common scenario AFAIK, but happy to take an open-source contribution for it. If you are interested, the code that installs Sysbox on K8s is [here](https://github.com/nestybox/sysbox-pkgr/tree/master/k8s). The main script that drives the installation is [here](https://github.com/nestybox/sysbox-pkgr/blob/master/k8s/scripts/sysbox-deploy-k8s.sh). That script runs inside the sysbox-deploy-k8s daemonset and "drops" Sysbox onto the host platform (WSL in your case), and reconfigures K8s to learn about Sysbox.

Hope that helps.
