### ISSUE TITLE
Can sysbox with systemd as ENTRYPOINT execute the other command after container start?

### ISSUE THREAD

**Issue by myugan** [nestybox/sysbox#94]
I need to run the docker container with systemd as PID 1 it means as ENTRYPOINT so I follow nestybox Dockerfile from here https://github.com/nestybox/dockerfiles/blob/main/ubuntu-bionic-systemd/Dockerfile but in this case, I need to run the custom bash script after container start but it doesn't execute the command:

```
FROM nestybox/ubuntu-bionic-systemd:latest
...
...
CMD [";docker-entrypoint.sh" ]
```

If I check the process list inside the container, systemd successfully loaded but `docker-entrypoint.sh` not executed.

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  77412  8352 ?        Ss   09:51   0:00 /sbin/init --log-level=err ;docker-entrypoint.sh
root       262  0.0  0.1  78476  9452 ?        Ss   09:51   0:00 /lib/systemd/systemd-journald
root       394  0.0  0.0  45012  3604 ?        Ss   09:51   0:00 /lib/systemd/systemd-udevd
systemd+   548  0.0  0.0  70656  5096 ?        Ss   09:51   0:00 /lib/systemd/systemd-resolved
root       759  0.0  0.0  28352  2712 ?        Ss   09:51   0:00 /usr/sbin/cron -f
```

**NOTE**: the script contains to initialize the data and other stuff.

So I need systemd to run in my **gitlab-runner** docker image and use docker inside it, any suggestion?

**Comment by rodnymolina** [comment]
@myugan, right, systemd never returns so that's why your custom entry-point is never executed, this is an expected behavior.

The usual best-practice in this case is to create a custom systemd service that handles all your initialization scripts. We just added [this](https://github.com/nestybox/dockerfiles/tree/main/ubuntu-focal-systemd-docker-custom) example as a reference. 

Hope that helps.

**Comment by rodnymolina** [comment]
@myugan, please let me know if the above approach was useful. If that's the case please close this one when have a chance.

**Comment by myugan** [comment]
Thankyou @rodnymolina it's very useful to know it.

**Comment by rodnymolina** [comment]
Will close now. Let us know if any other question on this matter.

**Comment by myugan** [comment]
Hi, @rodnymolina I found another issue when running systemd as entry point from sysbox Dockerfile examples.

```
ENTRYPOINT ["/sbin/init", "--log-level=err"]
```

The issue is `docker cp` can't copy the file from the host into `/tmp` directory inside a container, did you know about this? because I tried with Ubuntu image and the `cp` command works finely to copy the file into `/tmp` directory instead of using systemd when the container starts

**Comment by rodnymolina** [comment]
@myugan, can you please copy/paste the instructions that you are referring to?

**Comment by myugan** [comment]
This is the following command i used:

```
docker run -d --name demo -it nestybox/ubuntu-bionic-systemd:latest
echo "hello world" > hello.txt
docker cp hello.txt demo:/tmp
docker exec demo ls /tmp
```

**Comment by rodnymolina** [comment]
@myugan, i was able to reproduce the issue. Problem is related to the fact that "/tmp" is created as a tmpfs mount in the systemd scenario. Will take a closer look to the issue asap. As an obvious workaround, please make use of any other folder to copy files to within the sys container.

Also, it would be great if you could file a new issue with this new problem you have encountered, as this is different from your original question.

Thanks again for reporting this issue!

**Comment by rodnymolina** [comment]
@myugan, just fyi, we just fixed this secondary problem that you reported as part of this issue ("/tmp" directory handling). The fix went in as part of sysbox-runc PR [#20](https://github.com/nestybox/sysbox-runc/pull/20). You should be able to make us of /tmp as you see fit.

**Comment by DPatrickBoyd** [comment]
> @myugan, right, systemd never returns so that's why your custom entry-point is never executed, this is an expected behavior.
> 
> The usual best-practice in this case is to create a custom systemd service that handles all your initialization scripts. We just added [this](https://github.com/nestybox/dockerfiles/tree/main/ubuntu-focal-systemd-docker-custom) example as a reference.
> 
> Hope that helps.

This link is broken, interested in seeing how to use sysbox with systemd inside of nested containers

**Comment by rodnymolina** [comment]
@DPatrickBoyd, this is the new [link](https://github.com/nestybox/dockerfiles/tree/cdb9929fa837d6805892fb1b38a314e6743570e7/ubuntu-focal-systemd-docker-custom). Hope it helps.

**Comment by GramThanos** [comment]
There are some problems with this approach.
To start with the given custom code has some errors.

The the service does not have access to the environment variables of the container.
